#pragma once
#include <stdint.h>

// CPU Configuration (mpcore)

// 1 bank of scu

#define scu_BASE_ADDR 0xf8f00000U

// Registers

// SCU Control Register
#define scu_SCU_CONTROL_REGISTER_REG 0x0U
typedef union scu_SCU_CONTROL_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 25;
		uint32_t IC_STANDBY_ENABLE : 1;
		uint32_t SCU_STANDBY_ENABLE : 1;
		uint32_t FORCE_ALL_DEVICE_TO_PORT0_ENABLE : 1;
		uint32_t SCU_SPECULATIVE_LINEFILLS_ENABLE : 1;
		uint32_t SCU_RAMS_PARITY_ENABLE : 1;
		uint32_t ADDRESS_FILTERING_ENABLE : 1;
		uint32_t SCU_ENABLE : 1;
	} fields;
	uint32_t v;
} scu_SCU_CONTROL_REGISTER;

#define scu_SCU_CONTROL_REGISTER_RESERVED_0_LSHIFT 7U
#define scu_SCU_CONTROL_REGISTER_RESERVED_0_MASK 0xffffff80U
#define scu_SCU_CONTROL_REGISTER_IC_STANDBY_ENABLE_LSHIFT 6U
#define scu_SCU_CONTROL_REGISTER_IC_STANDBY_ENABLE 0x40U
#define scu_SCU_CONTROL_REGISTER_IC_STANDBY_ENABLE_MASK 0x40U
#define scu_SCU_CONTROL_REGISTER_SCU_STANDBY_ENABLE_LSHIFT 5U
#define scu_SCU_CONTROL_REGISTER_SCU_STANDBY_ENABLE 0x20U
#define scu_SCU_CONTROL_REGISTER_SCU_STANDBY_ENABLE_MASK 0x20U
#define scu_SCU_CONTROL_REGISTER_FORCE_ALL_DEVICE_TO_PORT0_ENABLE_LSHIFT 4U
#define scu_SCU_CONTROL_REGISTER_FORCE_ALL_DEVICE_TO_PORT0_ENABLE 0x10U
#define scu_SCU_CONTROL_REGISTER_FORCE_ALL_DEVICE_TO_PORT0_ENABLE_MASK 0x10U
#define scu_SCU_CONTROL_REGISTER_SCU_SPECULATIVE_LINEFILLS_ENABLE_LSHIFT 3U
#define scu_SCU_CONTROL_REGISTER_SCU_SPECULATIVE_LINEFILLS_ENABLE 0x8U
#define scu_SCU_CONTROL_REGISTER_SCU_SPECULATIVE_LINEFILLS_ENABLE_MASK 0x8U
#define scu_SCU_CONTROL_REGISTER_SCU_RAMS_PARITY_ENABLE_LSHIFT 2U
#define scu_SCU_CONTROL_REGISTER_SCU_RAMS_PARITY_ENABLE 0x4U
#define scu_SCU_CONTROL_REGISTER_SCU_RAMS_PARITY_ENABLE_MASK 0x4U
#define scu_SCU_CONTROL_REGISTER_ADDRESS_FILTERING_ENABLE_LSHIFT 1U
#define scu_SCU_CONTROL_REGISTER_ADDRESS_FILTERING_ENABLE 0x2U
#define scu_SCU_CONTROL_REGISTER_ADDRESS_FILTERING_ENABLE_MASK 0x2U
#define scu_SCU_CONTROL_REGISTER_SCU_ENABLE_LSHIFT 0U
#define scu_SCU_CONTROL_REGISTER_SCU_ENABLE 0x1U
#define scu_SCU_CONTROL_REGISTER_SCU_ENABLE_MASK 0x1U
#define scu_SCU_CONTROL_REGISTER_MASK 0x7fU


// SCU Configuration Register
#define scu_SCU_CONFIGURATION_REGISTER_REG 0x4U
typedef union scu_SCU_CONFIGURATION_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t TAG_RAM_SIZES : 8;
		uint32_t CPUS_SMP : 4;
		uint32_t RESERVED_1 : 2;
		uint32_t CPU_NUMBER : 2;
	} fields;
	uint32_t v;
} scu_SCU_CONFIGURATION_REGISTER;

#define scu_SCU_CONFIGURATION_REGISTER_RESERVED_0_LSHIFT 16U
#define scu_SCU_CONFIGURATION_REGISTER_RESERVED_0_MASK 0xffff0000U
#define scu_SCU_CONFIGURATION_REGISTER_TAG_RAM_SIZES_LSHIFT 8U
#define scu_SCU_CONFIGURATION_REGISTER_TAG_RAM_SIZES_MASK 0xff00U
#define scu_SCU_CONFIGURATION_REGISTER_CPUS_SMP_LSHIFT 4U
#define scu_SCU_CONFIGURATION_REGISTER_CPUS_SMP_MASK 0xf0U
#define scu_SCU_CONFIGURATION_REGISTER_RESERVED_1_LSHIFT 2U
#define scu_SCU_CONFIGURATION_REGISTER_RESERVED_1_MASK 0xcU
#define scu_SCU_CONFIGURATION_REGISTER_CPU_NUMBER_LSHIFT 0U
#define scu_SCU_CONFIGURATION_REGISTER_CPU_NUMBER_MASK 0x3U
#define scu_SCU_CONFIGURATION_REGISTER_MASK 0xfff3U


// SCU CPU Power Status Register
#define scu_SCU_CPU_POWER_STATUS_REGISTER_REG 0x8U
typedef union scu_SCU_CPU_POWER_STATUS_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t CPU3_STATUS : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t CPU2_STATUS : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t CPU1_STATUS : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t CPU0_STATUS : 2;
	} fields;
	uint32_t v;
} scu_SCU_CPU_POWER_STATUS_REGISTER;

#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_0_LSHIFT 26U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_0_MASK 0xfc000000U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU3_STATUS_LSHIFT 24U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU3_STATUS_MASK 0x3000000U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_1_LSHIFT 18U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_1_MASK 0xfc0000U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU2_STATUS_LSHIFT 16U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU2_STATUS_MASK 0x30000U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_2_LSHIFT 10U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_2_MASK 0xfc00U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU1_STATUS_LSHIFT 8U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU1_STATUS_MASK 0x300U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_3_LSHIFT 2U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_RESERVED_3_MASK 0xfcU
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU0_STATUS_LSHIFT 0U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_CPU0_STATUS_MASK 0x3U
#define scu_SCU_CPU_POWER_STATUS_REGISTER_MASK 0x3030303U


// SCU Invalidate All Registers in Secure State
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_REG 0xcU
typedef union scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t CPU3_WAYS : 4;
		uint32_t CPU2_WAYS : 4;
		uint32_t CPU1_WAYS : 4;
		uint32_t CPU0_WAYS : 4;
	} fields;
	uint32_t v;
} scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE;

#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_RESERVED_0_LSHIFT 16U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_RESERVED_0_MASK 0xffff0000U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU3_WAYS_LSHIFT 12U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU3_WAYS_MASK 0xf000U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU2_WAYS_LSHIFT 8U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU2_WAYS_MASK 0xf00U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU1_WAYS_LSHIFT 4U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU1_WAYS_MASK 0xf0U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU0_WAYS_LSHIFT 0U
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_CPU0_WAYS_MASK 0xfU
#define scu_SCU_INVALIDATE_ALL_REGISTERS_IN_SECURE_STATE_MASK 0xffffU


// Filtering Start Address Register
#define scu_FILTERING_START_ADDRESS_REGISTER_REG 0x40U
typedef union scu_FILTERING_START_ADDRESS_REGISTER
{
	struct
	{
		uint32_t FILTERING_START_ADDRESS : 12;
		uint32_t RESERVED_0 : 20;
	} fields;
	uint32_t v;
} scu_FILTERING_START_ADDRESS_REGISTER;

#define scu_FILTERING_START_ADDRESS_REGISTER_FILTERING_START_ADDRESS_LSHIFT 20U
#define scu_FILTERING_START_ADDRESS_REGISTER_FILTERING_START_ADDRESS_MASK 0xfff00000U
#define scu_FILTERING_START_ADDRESS_REGISTER_RESERVED_0_LSHIFT 0U
#define scu_FILTERING_START_ADDRESS_REGISTER_RESERVED_0_MASK 0xfffffU
#define scu_FILTERING_START_ADDRESS_REGISTER_MASK 0xfff00000U


// Defined by FILTEREND input
#define scu_FILTERING_END_ADDRESS_REGISTER_REG 0x44U
typedef union scu_FILTERING_END_ADDRESS_REGISTER
{
	struct
	{
		uint32_t FILTERING_END_ADDRESS : 12;
		uint32_t RESERVED_0 : 20;
	} fields;
	uint32_t v;
} scu_FILTERING_END_ADDRESS_REGISTER;

#define scu_FILTERING_END_ADDRESS_REGISTER_FILTERING_END_ADDRESS_LSHIFT 20U
#define scu_FILTERING_END_ADDRESS_REGISTER_FILTERING_END_ADDRESS_MASK 0xfff00000U
#define scu_FILTERING_END_ADDRESS_REGISTER_RESERVED_0_LSHIFT 0U
#define scu_FILTERING_END_ADDRESS_REGISTER_RESERVED_0_MASK 0xfffffU
#define scu_FILTERING_END_ADDRESS_REGISTER_MASK 0xfff00000U


// SCU Access Control (SAC) Register
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_REG 0x50U
typedef union scu_SCU_ACCESS_CONTROL_REGISTER_SAC
{
	struct
	{
		uint32_t RESERVED_0 : 28;
		uint32_t CPU3 : 1;
		uint32_t CPU2 : 1;
		uint32_t CPU1 : 1;
		uint32_t CPU0 : 1;
	} fields;
	uint32_t v;
} scu_SCU_ACCESS_CONTROL_REGISTER_SAC;

#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_RESERVED_0_LSHIFT 4U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_RESERVED_0_MASK 0xfffffff0U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU3_LSHIFT 3U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU3 0x8U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU3_MASK 0x8U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU2_LSHIFT 2U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU2 0x4U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU2_MASK 0x4U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU1_LSHIFT 1U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU1 0x2U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU1_MASK 0x2U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU0_LSHIFT 0U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU0 0x1U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_CPU0_MASK 0x1U
#define scu_SCU_ACCESS_CONTROL_REGISTER_SAC_MASK 0xfU


// SCU Non-secure Access Control Register SNSAC
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_REG 0x54U
typedef union scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER
{
	struct
	{
		uint32_t SBZ : 20;
		uint32_t CPU3_GLOBAL_TIMER : 1;
		uint32_t CPU2_GLOBAL_TIMER : 1;
		uint32_t CPU1_GLOBAL_TIMER : 1;
		uint32_t CPU0_GLOBAL_TIMER : 1;
		uint32_t PRIVATE_TIMERS_FOR_CPU3 : 1;
		uint32_t PRIVATE_TIMERS_FOR_CPU2 : 1;
		uint32_t PRIVATE_TIMERS_FOR_CPU1 : 1;
		uint32_t PRIVATE_TIMERS_FOR_CPU0 : 1;
		uint32_t COMPONENT_ACCESS_FOR_CPU3 : 1;
		uint32_t COMPONENT_ACCESS_FOR_CPU2 : 1;
		uint32_t COMPONENT_ACCESS_FOR_CPU1 : 1;
		uint32_t COMPONENT_ACCESS_FOR_CPU0 : 1;
	} fields;
	uint32_t v;
} scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER;

#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_SBZ_LSHIFT 12U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_SBZ_MASK 0xfffff000U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU3_GLOBAL_TIMER_LSHIFT 11U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU3_GLOBAL_TIMER 0x800U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU3_GLOBAL_TIMER_MASK 0x800U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU2_GLOBAL_TIMER_LSHIFT 10U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU2_GLOBAL_TIMER 0x400U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU2_GLOBAL_TIMER_MASK 0x400U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU1_GLOBAL_TIMER_LSHIFT 9U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU1_GLOBAL_TIMER 0x200U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU1_GLOBAL_TIMER_MASK 0x200U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU0_GLOBAL_TIMER_LSHIFT 8U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU0_GLOBAL_TIMER 0x100U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_CPU0_GLOBAL_TIMER_MASK 0x100U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU3_LSHIFT 7U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU3 0x80U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU3_MASK 0x80U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU2_LSHIFT 6U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU2 0x40U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU2_MASK 0x40U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU1_LSHIFT 5U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU1 0x20U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU1_MASK 0x20U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU0_LSHIFT 4U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU0 0x10U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_PRIVATE_TIMERS_FOR_CPU0_MASK 0x10U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU3_LSHIFT 3U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU3 0x8U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU3_MASK 0x8U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU2_LSHIFT 2U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU2 0x4U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU2_MASK 0x4U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU1_LSHIFT 1U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU1 0x2U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU1_MASK 0x2U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU0_LSHIFT 0U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU0 0x1U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_COMPONENT_ACCESS_FOR_CPU0_MASK 0x1U
#define scu_SCU_NON_SECURE_ACCESS_CONTROL_REGISTER_MASK 0xffffffffU


// CPU Interface Control Register
#define scu_ICCICR_REG 0x100U
typedef union scu_ICCICR
{
	struct
	{
		uint32_t RESERVED_0 : 27;
		uint32_t SBPR : 1;
		uint32_t FIQEN : 1;
		uint32_t ACKCTL : 1;
		uint32_t ENABLENS : 1;
		uint32_t ENABLES : 1;
	} fields;
	uint32_t v;
} scu_ICCICR;

#define scu_ICCICR_RESERVED_0_LSHIFT 5U
#define scu_ICCICR_RESERVED_0_MASK 0xffffffe0U
#define scu_ICCICR_SBPR_LSHIFT 4U
#define scu_ICCICR_SBPR 0x10U
#define scu_ICCICR_SBPR_MASK 0x10U
#define scu_ICCICR_FIQEN_LSHIFT 3U
#define scu_ICCICR_FIQEN 0x8U
#define scu_ICCICR_FIQEN_MASK 0x8U
#define scu_ICCICR_ACKCTL_LSHIFT 2U
#define scu_ICCICR_ACKCTL 0x4U
#define scu_ICCICR_ACKCTL_MASK 0x4U
#define scu_ICCICR_ENABLENS_LSHIFT 1U
#define scu_ICCICR_ENABLENS 0x2U
#define scu_ICCICR_ENABLENS_MASK 0x2U
#define scu_ICCICR_ENABLES_LSHIFT 0U
#define scu_ICCICR_ENABLES 0x1U
#define scu_ICCICR_ENABLES_MASK 0x1U
#define scu_ICCICR_MASK 0x1fU


// Interrupt Priority Mask Register
#define scu_ICCPMR_REG 0x104U
typedef union scu_ICCPMR
{
	struct
	{
		uint32_t RESERVED_0 : 24;
		uint32_t PRIORITY : 8;
	} fields;
	uint32_t v;
} scu_ICCPMR;

#define scu_ICCPMR_RESERVED_0_LSHIFT 8U
#define scu_ICCPMR_RESERVED_0_MASK 0xffffff00U
#define scu_ICCPMR_PRIORITY_LSHIFT 0U
#define scu_ICCPMR_PRIORITY_MASK 0xffU
#define scu_ICCPMR_MASK 0xffU


// Binary Point Register
#define scu_ICCBPR_REG 0x108U
typedef union scu_ICCBPR
{
	struct
	{
		uint32_t RESERVED_0 : 29;
		uint32_t BINARY_POINT : 3;
	} fields;
	uint32_t v;
} scu_ICCBPR;

#define scu_ICCBPR_RESERVED_0_LSHIFT 3U
#define scu_ICCBPR_RESERVED_0_MASK 0xfffffff8U
#define scu_ICCBPR_BINARY_POINT_LSHIFT 0U
#define scu_ICCBPR_BINARY_POINT_MASK 0x7U
#define scu_ICCBPR_MASK 0x7U


// Interrupt Acknowledge Register
#define scu_ICCIAR_REG 0x10cU
typedef union scu_ICCIAR
{
	struct
	{
		uint32_t RESERVED_0 : 19;
		uint32_t CPUID : 3;
		uint32_t ACKINTID : 10;
	} fields;
	uint32_t v;
} scu_ICCIAR;

#define scu_ICCIAR_RESERVED_0_LSHIFT 13U
#define scu_ICCIAR_RESERVED_0_MASK 0xffffe000U
#define scu_ICCIAR_CPUID_LSHIFT 10U
#define scu_ICCIAR_CPUID_MASK 0x1c00U
#define scu_ICCIAR_ACKINTID_LSHIFT 0U
#define scu_ICCIAR_ACKINTID_MASK 0x3ffU
#define scu_ICCIAR_MASK 0x1fffU


// End Of Interrupt Register
#define scu_ICCEOIR_REG 0x110U
typedef union scu_ICCEOIR
{
	struct
	{
		uint32_t RESERVED_0 : 19;
		uint32_t CPUID : 3;
		uint32_t EOIINTID : 10;
	} fields;
	uint32_t v;
} scu_ICCEOIR;

#define scu_ICCEOIR_RESERVED_0_LSHIFT 13U
#define scu_ICCEOIR_RESERVED_0_MASK 0xffffe000U
#define scu_ICCEOIR_CPUID_LSHIFT 10U
#define scu_ICCEOIR_CPUID_MASK 0x1c00U
#define scu_ICCEOIR_EOIINTID_LSHIFT 0U
#define scu_ICCEOIR_EOIINTID_MASK 0x3ffU
#define scu_ICCEOIR_MASK 0x1fffU


// Running Priority Register
#define scu_ICCRPR_REG 0x114U
typedef union scu_ICCRPR
{
	struct
	{
		uint32_t RESERVED_0 : 24;
		uint32_t PRIORITY : 8;
	} fields;
	uint32_t v;
} scu_ICCRPR;

#define scu_ICCRPR_RESERVED_0_LSHIFT 8U
#define scu_ICCRPR_RESERVED_0_MASK 0xffffff00U
#define scu_ICCRPR_PRIORITY_LSHIFT 0U
#define scu_ICCRPR_PRIORITY_MASK 0xffU
#define scu_ICCRPR_MASK 0xffU


// Highest Pending Interrupt Register
#define scu_ICCHPIR_REG 0x118U
typedef union scu_ICCHPIR
{
	struct
	{
		uint32_t RESERVED_0 : 19;
		uint32_t CPUID : 3;
		uint32_t PENDINTID : 10;
	} fields;
	uint32_t v;
} scu_ICCHPIR;

#define scu_ICCHPIR_RESERVED_0_LSHIFT 13U
#define scu_ICCHPIR_RESERVED_0_MASK 0xffffe000U
#define scu_ICCHPIR_CPUID_LSHIFT 10U
#define scu_ICCHPIR_CPUID_MASK 0x1c00U
#define scu_ICCHPIR_PENDINTID_LSHIFT 0U
#define scu_ICCHPIR_PENDINTID_MASK 0x3ffU
#define scu_ICCHPIR_MASK 0x1fffU


// Aliased Non-secure Binary Point Register
#define scu_ICCABPR_REG 0x11cU
typedef union scu_ICCABPR
{
	struct
	{
		uint32_t RESERVED_0 : 29;
		uint32_t BINARY_POINT : 3;
	} fields;
	uint32_t v;
} scu_ICCABPR;

#define scu_ICCABPR_RESERVED_0_LSHIFT 3U
#define scu_ICCABPR_RESERVED_0_MASK 0xfffffff8U
#define scu_ICCABPR_BINARY_POINT_LSHIFT 0U
#define scu_ICCABPR_BINARY_POINT_MASK 0x7U
#define scu_ICCABPR_MASK 0x7U


// CPU Interface Implementer Identification Register
#define scu_ICCIDR_REG 0x1fcU
typedef union scu_ICCIDR
{
	struct
	{
		uint32_t PART_NUMBER : 12;
		uint32_t ARCHITECTURE_VERSION : 4;
		uint32_t REVISION_NUMBER : 4;
		uint32_t IMPLEMENTER : 12;
	} fields;
	uint32_t v;
} scu_ICCIDR;

#define scu_ICCIDR_PART_NUMBER_LSHIFT 20U
#define scu_ICCIDR_PART_NUMBER_MASK 0xfff00000U
#define scu_ICCIDR_ARCHITECTURE_VERSION_LSHIFT 16U
#define scu_ICCIDR_ARCHITECTURE_VERSION_MASK 0xf0000U
#define scu_ICCIDR_REVISION_NUMBER_LSHIFT 12U
#define scu_ICCIDR_REVISION_NUMBER_MASK 0xf000U
#define scu_ICCIDR_IMPLEMENTER_LSHIFT 0U
#define scu_ICCIDR_IMPLEMENTER_MASK 0xfffU
#define scu_ICCIDR_MASK 0xffffffffU


// Global Timer Counter Register 0
#define scu_GLOBAL_TIMER_COUNTER_REGISTER0_REG 0x200U
typedef union scu_GLOBAL_TIMER_COUNTER_REGISTER0
{
	struct
	{
		uint32_t LOW : 32;
	} fields;
	uint32_t v;
} scu_GLOBAL_TIMER_COUNTER_REGISTER0;

#define scu_GLOBAL_TIMER_COUNTER_REGISTER0_LOW_LSHIFT 0U
#define scu_GLOBAL_TIMER_COUNTER_REGISTER0_LOW_MASK 0x0U
#define scu_GLOBAL_TIMER_COUNTER_REGISTER0_MASK 0x0U


// Global Timer Counter Register 1
#define scu_GLOBAL_TIMER_COUNTER_REGISTER1_REG 0x204U
typedef union scu_GLOBAL_TIMER_COUNTER_REGISTER1
{
	struct
	{
		uint32_t HIGH : 32;
	} fields;
	uint32_t v;
} scu_GLOBAL_TIMER_COUNTER_REGISTER1;

#define scu_GLOBAL_TIMER_COUNTER_REGISTER1_HIGH_LSHIFT 0U
#define scu_GLOBAL_TIMER_COUNTER_REGISTER1_HIGH_MASK 0x0U
#define scu_GLOBAL_TIMER_COUNTER_REGISTER1_MASK 0x0U


// Global Timer Control Register 
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_REG 0x208U
typedef union scu_GLOBAL_TIMER_CONTROL_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t PRESCALER : 8;
		uint32_t RESERVED_1 : 4;
		uint32_t MODE : 1;
		uint32_t IRQ_ENABLE : 1;
		uint32_t COMP_ENABLEA : 1;
		uint32_t TIMER_ENABLE : 1;
	} fields;
	uint32_t v;
} scu_GLOBAL_TIMER_CONTROL_REGISTER;

#define scu_GLOBAL_TIMER_CONTROL_REGISTER_RESERVED_0_LSHIFT 16U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_RESERVED_0_MASK 0xffff0000U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_PRESCALER_LSHIFT 8U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_PRESCALER_MASK 0xff00U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_RESERVED_1_LSHIFT 4U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_RESERVED_1_MASK 0xf0U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_MODE_LSHIFT 3U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_MODE 0x8U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_MODE_MASK 0x8U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_IRQ_ENABLE_LSHIFT 2U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_IRQ_ENABLE 0x4U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_IRQ_ENABLE_MASK 0x4U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_COMP_ENABLEA_LSHIFT 1U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_COMP_ENABLEA 0x2U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_COMP_ENABLEA_MASK 0x2U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_TIMER_ENABLE_LSHIFT 0U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_TIMER_ENABLE 0x1U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_TIMER_ENABLE_MASK 0x1U
#define scu_GLOBAL_TIMER_CONTROL_REGISTER_MASK 0xff0fU


// Global Timer Interrupt Status Register 
#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_REG 0x20cU
typedef union scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 31;
		uint32_t EVENT_FLAG : 1;
	} fields;
	uint32_t v;
} scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER;

#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_RESERVED_0_LSHIFT 1U
#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_RESERVED_0_MASK 0xfffffffeU
#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_EVENT_FLAG_LSHIFT 0U
#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_EVENT_FLAG 0x1U
#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_EVENT_FLAG_MASK 0x1U
#define scu_GLOBAL_TIMER_INTERRUPT_STATUS_REGISTER_MASK 0x1U


// Comparator Value Register_0 
#define scu_COMPARATOR_VALUE_REGISTER0_REG 0x210U
typedef union scu_COMPARATOR_VALUE_REGISTER0
{
	struct
	{
		uint32_t LOW : 32;
	} fields;
	uint32_t v;
} scu_COMPARATOR_VALUE_REGISTER0;

#define scu_COMPARATOR_VALUE_REGISTER0_LOW_LSHIFT 0U
#define scu_COMPARATOR_VALUE_REGISTER0_LOW_MASK 0x0U
#define scu_COMPARATOR_VALUE_REGISTER0_MASK 0x0U


// Comparator Value Register_1
#define scu_COMPARATOR_VALUE_REGISTER1_REG 0x214U
typedef union scu_COMPARATOR_VALUE_REGISTER1
{
	struct
	{
		uint32_t HIGH : 32;
	} fields;
	uint32_t v;
} scu_COMPARATOR_VALUE_REGISTER1;

#define scu_COMPARATOR_VALUE_REGISTER1_HIGH_LSHIFT 0U
#define scu_COMPARATOR_VALUE_REGISTER1_HIGH_MASK 0x0U
#define scu_COMPARATOR_VALUE_REGISTER1_MASK 0x0U


// Auto-increment Register 
#define scu_AUTO_INCREMENT_REGISTER_REG 0x218U
typedef union scu_AUTO_INCREMENT_REGISTER
{
	struct
	{
		uint32_t INCR : 32;
	} fields;
	uint32_t v;
} scu_AUTO_INCREMENT_REGISTER;

#define scu_AUTO_INCREMENT_REGISTER_INCR_LSHIFT 0U
#define scu_AUTO_INCREMENT_REGISTER_INCR_MASK 0x0U
#define scu_AUTO_INCREMENT_REGISTER_MASK 0x0U


// Private Timer Load Register 
#define scu_PRIVATE_TIMER_LOAD_REGISTER_REG 0x600U
typedef union scu_PRIVATE_TIMER_LOAD_REGISTER
{
	struct
	{
		uint32_t LOAD : 32;
	} fields;
	uint32_t v;
} scu_PRIVATE_TIMER_LOAD_REGISTER;

#define scu_PRIVATE_TIMER_LOAD_REGISTER_LOAD_LSHIFT 0U
#define scu_PRIVATE_TIMER_LOAD_REGISTER_LOAD_MASK 0x0U
#define scu_PRIVATE_TIMER_LOAD_REGISTER_MASK 0x0U


// Private Timer Counter Register 
#define scu_PRIVATE_TIMER_COUNTER_REGISTER_REG 0x604U
typedef union scu_PRIVATE_TIMER_COUNTER_REGISTER
{
	struct
	{
		uint32_t COUNTER : 32;
	} fields;
	uint32_t v;
} scu_PRIVATE_TIMER_COUNTER_REGISTER;

#define scu_PRIVATE_TIMER_COUNTER_REGISTER_COUNTER_LSHIFT 0U
#define scu_PRIVATE_TIMER_COUNTER_REGISTER_COUNTER_MASK 0x0U
#define scu_PRIVATE_TIMER_COUNTER_REGISTER_MASK 0x0U


// Private Timer Control Register 
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_REG 0x608U
typedef union scu_PRIVATE_TIMER_CONTROL_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t PRESCALER : 8;
		uint32_t RESERVED_1 : 5;
		uint32_t IRQ_ENABLE : 1;
		uint32_t AUTO_RELOAD : 1;
		uint32_t TIMER_ENABLE : 1;
	} fields;
	uint32_t v;
} scu_PRIVATE_TIMER_CONTROL_REGISTER;

#define scu_PRIVATE_TIMER_CONTROL_REGISTER_RESERVED_0_LSHIFT 16U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_RESERVED_0_MASK 0xffff0000U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_PRESCALER_LSHIFT 8U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_PRESCALER_MASK 0xff00U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_RESERVED_1_LSHIFT 3U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_RESERVED_1_MASK 0xf8U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_IRQ_ENABLE_LSHIFT 2U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_IRQ_ENABLE 0x4U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_IRQ_ENABLE_MASK 0x4U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_AUTO_RELOAD_LSHIFT 1U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_AUTO_RELOAD 0x2U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_AUTO_RELOAD_MASK 0x2U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_TIMER_ENABLE_LSHIFT 0U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_TIMER_ENABLE 0x1U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_TIMER_ENABLE_MASK 0x1U
#define scu_PRIVATE_TIMER_CONTROL_REGISTER_MASK 0xff07U


// Private Timer Interrupt Status Register 
#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_REG 0x60cU
typedef union scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 31;
		uint32_t EVENT : 1;
	} fields;
	uint32_t v;
} scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER;

#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_RESERVED_0_LSHIFT 1U
#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_RESERVED_0_MASK 0xfffffffeU
#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_EVENT_LSHIFT 0U
#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_EVENT 0x1U
#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_EVENT_MASK 0x1U
#define scu_PRIVATE_TIMER_INTERRUPT_STATUS_REGISTER_MASK 0x1U


// Watchdog Load Register 
#define scu_WATCHDOG_LOAD_REGISTER_REG 0x620U
typedef union scu_WATCHDOG_LOAD_REGISTER
{
	struct
	{
		uint32_t LOAD : 32;
	} fields;
	uint32_t v;
} scu_WATCHDOG_LOAD_REGISTER;

#define scu_WATCHDOG_LOAD_REGISTER_LOAD_LSHIFT 0U
#define scu_WATCHDOG_LOAD_REGISTER_LOAD_MASK 0x0U
#define scu_WATCHDOG_LOAD_REGISTER_MASK 0x0U


// Watchdog Counter Register 
#define scu_WATCHDOG_COUNTER_REGISTER_REG 0x624U
typedef union scu_WATCHDOG_COUNTER_REGISTER
{
	struct
	{
		uint32_t COUNTER : 32;
	} fields;
	uint32_t v;
} scu_WATCHDOG_COUNTER_REGISTER;

#define scu_WATCHDOG_COUNTER_REGISTER_COUNTER_LSHIFT 0U
#define scu_WATCHDOG_COUNTER_REGISTER_COUNTER_MASK 0x0U
#define scu_WATCHDOG_COUNTER_REGISTER_MASK 0x0U


// Watchdog Control Register 
#define scu_WATCHDOG_CONTROL_REGISTER_REG 0x628U
typedef union scu_WATCHDOG_CONTROL_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t PRESCALER : 8;
		uint32_t RESERVED_1 : 4;
		uint32_t WATCHDOG_MODE : 1;
		uint32_t IT_ENABLE : 1;
		uint32_t AUTO_RELOAD : 1;
		uint32_t WATCHDOG_ENABLE : 1;
	} fields;
	uint32_t v;
} scu_WATCHDOG_CONTROL_REGISTER;

#define scu_WATCHDOG_CONTROL_REGISTER_RESERVED_0_LSHIFT 16U
#define scu_WATCHDOG_CONTROL_REGISTER_RESERVED_0_MASK 0xffff0000U
#define scu_WATCHDOG_CONTROL_REGISTER_PRESCALER_LSHIFT 8U
#define scu_WATCHDOG_CONTROL_REGISTER_PRESCALER_MASK 0xff00U
#define scu_WATCHDOG_CONTROL_REGISTER_RESERVED_1_LSHIFT 4U
#define scu_WATCHDOG_CONTROL_REGISTER_RESERVED_1_MASK 0xf0U
#define scu_WATCHDOG_CONTROL_REGISTER_WATCHDOG_MODE_LSHIFT 3U
#define scu_WATCHDOG_CONTROL_REGISTER_WATCHDOG_MODE 0x8U
#define scu_WATCHDOG_CONTROL_REGISTER_WATCHDOG_MODE_MASK 0x8U
#define scu_WATCHDOG_CONTROL_REGISTER_IT_ENABLE_LSHIFT 2U
#define scu_WATCHDOG_CONTROL_REGISTER_IT_ENABLE 0x4U
#define scu_WATCHDOG_CONTROL_REGISTER_IT_ENABLE_MASK 0x4U
#define scu_WATCHDOG_CONTROL_REGISTER_AUTO_RELOAD_LSHIFT 1U
#define scu_WATCHDOG_CONTROL_REGISTER_AUTO_RELOAD 0x2U
#define scu_WATCHDOG_CONTROL_REGISTER_AUTO_RELOAD_MASK 0x2U
#define scu_WATCHDOG_CONTROL_REGISTER_WATCHDOG_ENABLE_LSHIFT 0U
#define scu_WATCHDOG_CONTROL_REGISTER_WATCHDOG_ENABLE 0x1U
#define scu_WATCHDOG_CONTROL_REGISTER_WATCHDOG_ENABLE_MASK 0x1U
#define scu_WATCHDOG_CONTROL_REGISTER_MASK 0xff0fU


// Watchdog Interrupt Status Register 
#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_REG 0x62cU
typedef union scu_WATCHDOG_INTERRUPT_STATUS_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 31;
		uint32_t EVENT_FLAG : 1;
	} fields;
	uint32_t v;
} scu_WATCHDOG_INTERRUPT_STATUS_REGISTER;

#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_RESERVED_0_LSHIFT 1U
#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_RESERVED_0_MASK 0xfffffffeU
#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_EVENT_FLAG_LSHIFT 0U
#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_EVENT_FLAG 0x1U
#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_EVENT_FLAG_MASK 0x1U
#define scu_WATCHDOG_INTERRUPT_STATUS_REGISTER_MASK 0x1U


// Watchdog Reset Status Register 
#define scu_WATCHDOG_RESET_STATUS_REGISTER_REG 0x630U
typedef union scu_WATCHDOG_RESET_STATUS_REGISTER
{
	struct
	{
		uint32_t RESERVED_0 : 31;
		uint32_t RESET_FLAG : 1;
	} fields;
	uint32_t v;
} scu_WATCHDOG_RESET_STATUS_REGISTER;

#define scu_WATCHDOG_RESET_STATUS_REGISTER_RESERVED_0_LSHIFT 1U
#define scu_WATCHDOG_RESET_STATUS_REGISTER_RESERVED_0_MASK 0xfffffffeU
#define scu_WATCHDOG_RESET_STATUS_REGISTER_RESET_FLAG_LSHIFT 0U
#define scu_WATCHDOG_RESET_STATUS_REGISTER_RESET_FLAG 0x1U
#define scu_WATCHDOG_RESET_STATUS_REGISTER_RESET_FLAG_MASK 0x1U
#define scu_WATCHDOG_RESET_STATUS_REGISTER_MASK 0x1U


// Watchdog Disable Register
#define scu_WATCHDOG_DISABLE_REGISTER_REG 0x634U
typedef union scu_WATCHDOG_DISABLE_REGISTER
{
	struct
	{
		uint32_t DISABLE : 32;
	} fields;
	uint32_t v;
} scu_WATCHDOG_DISABLE_REGISTER;

#define scu_WATCHDOG_DISABLE_REGISTER_DISABLE_LSHIFT 0U
#define scu_WATCHDOG_DISABLE_REGISTER_DISABLE_MASK 0x0U
#define scu_WATCHDOG_DISABLE_REGISTER_MASK 0x0U


// Distributor Control Register
#define scu_ICDDCR_REG 0x1000U
typedef union scu_ICDDCR
{
	struct
	{
		uint32_t RESERVED_0 : 30;
		uint32_t ENABLE_NON_SECURE : 1;
		uint32_t ENABLE_SECURE : 1;
	} fields;
	uint32_t v;
} scu_ICDDCR;

#define scu_ICDDCR_RESERVED_0_LSHIFT 2U
#define scu_ICDDCR_RESERVED_0_MASK 0xfffffffcU
#define scu_ICDDCR_ENABLE_NON_SECURE_LSHIFT 1U
#define scu_ICDDCR_ENABLE_NON_SECURE 0x2U
#define scu_ICDDCR_ENABLE_NON_SECURE_MASK 0x2U
#define scu_ICDDCR_ENABLE_SECURE_LSHIFT 0U
#define scu_ICDDCR_ENABLE_SECURE 0x1U
#define scu_ICDDCR_ENABLE_SECURE_MASK 0x1U
#define scu_ICDDCR_MASK 0x3U


// Interrupt Controller Type Register
#define scu_ICDICTR_REG 0x1004U
typedef union scu_ICDICTR
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t LSPI : 5;
		uint32_t SECURITYEXTN : 1;
		uint32_t RESERVED_1 : 2;
		uint32_t CPU_NUMBER : 3;
		uint32_t IT_LINES_NUMBER : 5;
	} fields;
	uint32_t v;
} scu_ICDICTR;

#define scu_ICDICTR_RESERVED_0_LSHIFT 16U
#define scu_ICDICTR_RESERVED_0_MASK 0xffff0000U
#define scu_ICDICTR_LSPI_LSHIFT 11U
#define scu_ICDICTR_LSPI_MASK 0xf800U
#define scu_ICDICTR_SECURITYEXTN_LSHIFT 10U
#define scu_ICDICTR_SECURITYEXTN 0x400U
#define scu_ICDICTR_SECURITYEXTN_MASK 0x400U
#define scu_ICDICTR_RESERVED_1_LSHIFT 8U
#define scu_ICDICTR_RESERVED_1_MASK 0x300U
#define scu_ICDICTR_CPU_NUMBER_LSHIFT 5U
#define scu_ICDICTR_CPU_NUMBER_MASK 0xe0U
#define scu_ICDICTR_IT_LINES_NUMBER_LSHIFT 0U
#define scu_ICDICTR_IT_LINES_NUMBER_MASK 0x1fU
#define scu_ICDICTR_MASK 0xfcffU


// Distributor Implementer Identification Register
#define scu_ICDIIDR_REG 0x1008U
typedef union scu_ICDIIDR
{
	struct
	{
		uint32_t IMPLEMENTATION_VERSION : 8;
		uint32_t REVISION_NUMBER : 12;
		uint32_t IMPLEMENTER : 12;
	} fields;
	uint32_t v;
} scu_ICDIIDR;

#define scu_ICDIIDR_IMPLEMENTATION_VERSION_LSHIFT 24U
#define scu_ICDIIDR_IMPLEMENTATION_VERSION_MASK 0xff000000U
#define scu_ICDIIDR_REVISION_NUMBER_LSHIFT 12U
#define scu_ICDIIDR_REVISION_NUMBER_MASK 0xfff000U
#define scu_ICDIIDR_IMPLEMENTER_LSHIFT 0U
#define scu_ICDIIDR_IMPLEMENTER_MASK 0xfffU
#define scu_ICDIIDR_MASK 0xffffffffU


// Interrupt Security Register_0
#define scu_ICDISR0_REG 0x1080U
typedef union scu_ICDISR0
{
	struct
	{
		uint32_t SECURITY_STATUS : 32;
	} fields;
	uint32_t v;
} scu_ICDISR0;

#define scu_ICDISR0_SECURITY_STATUS_LSHIFT 0U
#define scu_ICDISR0_SECURITY_STATUS_MASK 0x0U
#define scu_ICDISR0_MASK 0x0U


// Interrupt Security Register_1
#define scu_ICDISR1_REG 0x1084U
typedef union scu_ICDISR1
{
	struct
	{
		uint32_t SECURITY_STATUS : 32;
	} fields;
	uint32_t v;
} scu_ICDISR1;

#define scu_ICDISR1_SECURITY_STATUS_LSHIFT 0U
#define scu_ICDISR1_SECURITY_STATUS_MASK 0x0U
#define scu_ICDISR1_MASK 0x0U


// Interrupt Security Register_2
#define scu_ICDISR2_REG 0x1088U
typedef union scu_ICDISR2
{
	struct
	{
		uint32_t SECURITY_STATUS : 32;
	} fields;
	uint32_t v;
} scu_ICDISR2;

#define scu_ICDISR2_SECURITY_STATUS_LSHIFT 0U
#define scu_ICDISR2_SECURITY_STATUS_MASK 0x0U
#define scu_ICDISR2_MASK 0x0U


// Interrupt Set-enable Register 0
#define scu_ICDISER0_REG 0x1100U
typedef union scu_ICDISER0
{
	struct
	{
		uint32_t SET : 32;
	} fields;
	uint32_t v;
} scu_ICDISER0;

#define scu_ICDISER0_SET_LSHIFT 0U
#define scu_ICDISER0_SET_MASK 0x0U
#define scu_ICDISER0_MASK 0x0U


// Interrupt Set-enable Register 1
#define scu_ICDISER1_REG 0x1104U
typedef union scu_ICDISER1
{
	struct
	{
		uint32_t SET : 32;
	} fields;
	uint32_t v;
} scu_ICDISER1;

#define scu_ICDISER1_SET_LSHIFT 0U
#define scu_ICDISER1_SET_MASK 0x0U
#define scu_ICDISER1_MASK 0x0U


// Interrupt Set-enable Register 2
#define scu_ICDISER2_REG 0x1108U
typedef union scu_ICDISER2
{
	struct
	{
		uint32_t SET : 32;
	} fields;
	uint32_t v;
} scu_ICDISER2;

#define scu_ICDISER2_SET_LSHIFT 0U
#define scu_ICDISER2_SET_MASK 0x0U
#define scu_ICDISER2_MASK 0x0U


// Interrupt Clear-Enable Register 0
#define scu_ICDICER0_REG 0x1180U
typedef union scu_ICDICER0
{
	struct
	{
		uint32_t CLEAR : 32;
	} fields;
	uint32_t v;
} scu_ICDICER0;

#define scu_ICDICER0_CLEAR_LSHIFT 0U
#define scu_ICDICER0_CLEAR_MASK 0x0U
#define scu_ICDICER0_MASK 0x0U


// Interrupt Clear-Enable Register 1
#define scu_ICDICER1_REG 0x1184U
typedef union scu_ICDICER1
{
	struct
	{
		uint32_t CLEAR : 32;
	} fields;
	uint32_t v;
} scu_ICDICER1;

#define scu_ICDICER1_CLEAR_LSHIFT 0U
#define scu_ICDICER1_CLEAR_MASK 0x0U
#define scu_ICDICER1_MASK 0x0U


// Interrupt Clear-Enable Register 2
#define scu_ICDICER2_REG 0x1188U
typedef union scu_ICDICER2
{
	struct
	{
		uint32_t CLEAR : 32;
	} fields;
	uint32_t v;
} scu_ICDICER2;

#define scu_ICDICER2_CLEAR_LSHIFT 0U
#define scu_ICDICER2_CLEAR_MASK 0x0U
#define scu_ICDICER2_MASK 0x0U


// Interrupt Set-pending Register_0
#define scu_ICDISPR0_REG 0x1200U
typedef union scu_ICDISPR0
{
	struct
	{
		uint32_t SET : 32;
	} fields;
	uint32_t v;
} scu_ICDISPR0;

#define scu_ICDISPR0_SET_LSHIFT 0U
#define scu_ICDISPR0_SET_MASK 0x0U
#define scu_ICDISPR0_MASK 0x0U


// Interrupt Set-pending Register_1
#define scu_ICDISPR1_REG 0x1204U
typedef union scu_ICDISPR1
{
	struct
	{
		uint32_t SET : 32;
	} fields;
	uint32_t v;
} scu_ICDISPR1;

#define scu_ICDISPR1_SET_LSHIFT 0U
#define scu_ICDISPR1_SET_MASK 0x0U
#define scu_ICDISPR1_MASK 0x0U


// Interrupt Set-pending Register_2
#define scu_ICDISPR2_REG 0x1208U
typedef union scu_ICDISPR2
{
	struct
	{
		uint32_t SET : 32;
	} fields;
	uint32_t v;
} scu_ICDISPR2;

#define scu_ICDISPR2_SET_LSHIFT 0U
#define scu_ICDISPR2_SET_MASK 0x0U
#define scu_ICDISPR2_MASK 0x0U


// Interrupt Clear-Pending Register_0
#define scu_ICDICPR0_REG 0x1280U
typedef union scu_ICDICPR0
{
	struct
	{
		uint32_t CLEAR : 32;
	} fields;
	uint32_t v;
} scu_ICDICPR0;

#define scu_ICDICPR0_CLEAR_LSHIFT 0U
#define scu_ICDICPR0_CLEAR_MASK 0x0U
#define scu_ICDICPR0_MASK 0x0U


// Interrupt Clear-Pending Register_1
#define scu_ICDICPR1_REG 0x1284U
typedef union scu_ICDICPR1
{
	struct
	{
		uint32_t CLEAR : 32;
	} fields;
	uint32_t v;
} scu_ICDICPR1;

#define scu_ICDICPR1_CLEAR_LSHIFT 0U
#define scu_ICDICPR1_CLEAR_MASK 0x0U
#define scu_ICDICPR1_MASK 0x0U


// Interrupt Clear-Pending Register_2
#define scu_ICDICPR2_REG 0x1288U
typedef union scu_ICDICPR2
{
	struct
	{
		uint32_t CLEAR : 32;
	} fields;
	uint32_t v;
} scu_ICDICPR2;

#define scu_ICDICPR2_CLEAR_LSHIFT 0U
#define scu_ICDICPR2_CLEAR_MASK 0x0U
#define scu_ICDICPR2_MASK 0x0U


// Active Bit register_0
#define scu_ICDABR0_REG 0x1300U
typedef union scu_ICDABR0
{
	struct
	{
		uint32_t ACTIVE : 32;
	} fields;
	uint32_t v;
} scu_ICDABR0;

#define scu_ICDABR0_ACTIVE_LSHIFT 0U
#define scu_ICDABR0_ACTIVE_MASK 0x0U
#define scu_ICDABR0_MASK 0x0U


// Active Bit register_1
#define scu_ICDABR1_REG 0x1304U
typedef union scu_ICDABR1
{
	struct
	{
		uint32_t ACTIVE : 32;
	} fields;
	uint32_t v;
} scu_ICDABR1;

#define scu_ICDABR1_ACTIVE_LSHIFT 0U
#define scu_ICDABR1_ACTIVE_MASK 0x0U
#define scu_ICDABR1_MASK 0x0U


// Active Bit register_2
#define scu_ICDABR2_REG 0x1308U
typedef union scu_ICDABR2
{
	struct
	{
		uint32_t ACTIVE : 32;
	} fields;
	uint32_t v;
} scu_ICDABR2;

#define scu_ICDABR2_ACTIVE_LSHIFT 0U
#define scu_ICDABR2_ACTIVE_MASK 0x0U
#define scu_ICDABR2_MASK 0x0U


// Interrupt Priority Register_0
#define scu_ICDIPR0_REG 0x1400U
typedef union scu_ICDIPR0
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR0;

#define scu_ICDIPR0_PRIORITY_LSHIFT 0U
#define scu_ICDIPR0_PRIORITY_MASK 0x0U
#define scu_ICDIPR0_MASK 0x0U


// Interrupt Priority Register_1
#define scu_ICDIPR1_REG 0x1404U
typedef union scu_ICDIPR1
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR1;

#define scu_ICDIPR1_PRIORITY_LSHIFT 0U
#define scu_ICDIPR1_PRIORITY_MASK 0x0U
#define scu_ICDIPR1_MASK 0x0U


// Interrupt Priority Register_2
#define scu_ICDIPR2_REG 0x1408U
typedef union scu_ICDIPR2
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR2;

#define scu_ICDIPR2_PRIORITY_LSHIFT 0U
#define scu_ICDIPR2_PRIORITY_MASK 0x0U
#define scu_ICDIPR2_MASK 0x0U


// Interrupt Priority Register_3
#define scu_ICDIPR3_REG 0x140cU
typedef union scu_ICDIPR3
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR3;

#define scu_ICDIPR3_PRIORITY_LSHIFT 0U
#define scu_ICDIPR3_PRIORITY_MASK 0x0U
#define scu_ICDIPR3_MASK 0x0U


// Interrupt Priority Register_4
#define scu_ICDIPR4_REG 0x1410U
typedef union scu_ICDIPR4
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR4;

#define scu_ICDIPR4_PRIORITY_LSHIFT 0U
#define scu_ICDIPR4_PRIORITY_MASK 0x0U
#define scu_ICDIPR4_MASK 0x0U


// Interrupt Priority Register_5
#define scu_ICDIPR5_REG 0x1414U
typedef union scu_ICDIPR5
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR5;

#define scu_ICDIPR5_PRIORITY_LSHIFT 0U
#define scu_ICDIPR5_PRIORITY_MASK 0x0U
#define scu_ICDIPR5_MASK 0x0U


// Interrupt Priority Register_6
#define scu_ICDIPR6_REG 0x1418U
typedef union scu_ICDIPR6
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR6;

#define scu_ICDIPR6_PRIORITY_LSHIFT 0U
#define scu_ICDIPR6_PRIORITY_MASK 0x0U
#define scu_ICDIPR6_MASK 0x0U


// Interrupt Priority Register_7
#define scu_ICDIPR7_REG 0x141cU
typedef union scu_ICDIPR7
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR7;

#define scu_ICDIPR7_PRIORITY_LSHIFT 0U
#define scu_ICDIPR7_PRIORITY_MASK 0x0U
#define scu_ICDIPR7_MASK 0x0U


// Interrupt Priority Register_8
#define scu_ICDIPR8_REG 0x1420U
typedef union scu_ICDIPR8
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR8;

#define scu_ICDIPR8_PRIORITY_LSHIFT 0U
#define scu_ICDIPR8_PRIORITY_MASK 0x0U
#define scu_ICDIPR8_MASK 0x0U


// Interrupt Priority Register_9
#define scu_ICDIPR9_REG 0x1424U
typedef union scu_ICDIPR9
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR9;

#define scu_ICDIPR9_PRIORITY_LSHIFT 0U
#define scu_ICDIPR9_PRIORITY_MASK 0x0U
#define scu_ICDIPR9_MASK 0x0U


// Interrupt Priority Register_10
#define scu_ICDIPR10_REG 0x1428U
typedef union scu_ICDIPR10
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR10;

#define scu_ICDIPR10_PRIORITY_LSHIFT 0U
#define scu_ICDIPR10_PRIORITY_MASK 0x0U
#define scu_ICDIPR10_MASK 0x0U


// Interrupt Priority Register_11
#define scu_ICDIPR11_REG 0x142cU
typedef union scu_ICDIPR11
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR11;

#define scu_ICDIPR11_PRIORITY_LSHIFT 0U
#define scu_ICDIPR11_PRIORITY_MASK 0x0U
#define scu_ICDIPR11_MASK 0x0U


// Interrupt Priority Register_12
#define scu_ICDIPR12_REG 0x1430U
typedef union scu_ICDIPR12
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR12;

#define scu_ICDIPR12_PRIORITY_LSHIFT 0U
#define scu_ICDIPR12_PRIORITY_MASK 0x0U
#define scu_ICDIPR12_MASK 0x0U


// Interrupt Priority Register_13
#define scu_ICDIPR13_REG 0x1434U
typedef union scu_ICDIPR13
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR13;

#define scu_ICDIPR13_PRIORITY_LSHIFT 0U
#define scu_ICDIPR13_PRIORITY_MASK 0x0U
#define scu_ICDIPR13_MASK 0x0U


// Interrupt Priority Register_14
#define scu_ICDIPR14_REG 0x1438U
typedef union scu_ICDIPR14
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR14;

#define scu_ICDIPR14_PRIORITY_LSHIFT 0U
#define scu_ICDIPR14_PRIORITY_MASK 0x0U
#define scu_ICDIPR14_MASK 0x0U


// Interrupt Priority Register_15
#define scu_ICDIPR15_REG 0x143cU
typedef union scu_ICDIPR15
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR15;

#define scu_ICDIPR15_PRIORITY_LSHIFT 0U
#define scu_ICDIPR15_PRIORITY_MASK 0x0U
#define scu_ICDIPR15_MASK 0x0U


// Interrupt Priority Register_16
#define scu_ICDIPR16_REG 0x1440U
typedef union scu_ICDIPR16
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR16;

#define scu_ICDIPR16_PRIORITY_LSHIFT 0U
#define scu_ICDIPR16_PRIORITY_MASK 0x0U
#define scu_ICDIPR16_MASK 0x0U


// Interrupt Priority Register_17
#define scu_ICDIPR17_REG 0x1444U
typedef union scu_ICDIPR17
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR17;

#define scu_ICDIPR17_PRIORITY_LSHIFT 0U
#define scu_ICDIPR17_PRIORITY_MASK 0x0U
#define scu_ICDIPR17_MASK 0x0U


// Interrupt Priority Register_18
#define scu_ICDIPR18_REG 0x1448U
typedef union scu_ICDIPR18
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR18;

#define scu_ICDIPR18_PRIORITY_LSHIFT 0U
#define scu_ICDIPR18_PRIORITY_MASK 0x0U
#define scu_ICDIPR18_MASK 0x0U


// Interrupt Priority Register_19
#define scu_ICDIPR19_REG 0x144cU
typedef union scu_ICDIPR19
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR19;

#define scu_ICDIPR19_PRIORITY_LSHIFT 0U
#define scu_ICDIPR19_PRIORITY_MASK 0x0U
#define scu_ICDIPR19_MASK 0x0U


// Interrupt Priority Register_20
#define scu_ICDIPR20_REG 0x1450U
typedef union scu_ICDIPR20
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR20;

#define scu_ICDIPR20_PRIORITY_LSHIFT 0U
#define scu_ICDIPR20_PRIORITY_MASK 0x0U
#define scu_ICDIPR20_MASK 0x0U


// Interrupt Priority Register_21
#define scu_ICDIPR21_REG 0x1454U
typedef union scu_ICDIPR21
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR21;

#define scu_ICDIPR21_PRIORITY_LSHIFT 0U
#define scu_ICDIPR21_PRIORITY_MASK 0x0U
#define scu_ICDIPR21_MASK 0x0U


// Interrupt Priority Register_22
#define scu_ICDIPR22_REG 0x1458U
typedef union scu_ICDIPR22
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR22;

#define scu_ICDIPR22_PRIORITY_LSHIFT 0U
#define scu_ICDIPR22_PRIORITY_MASK 0x0U
#define scu_ICDIPR22_MASK 0x0U


// Interrupt Priority Register_23
#define scu_ICDIPR23_REG 0x145cU
typedef union scu_ICDIPR23
{
	struct
	{
		uint32_t PRIORITY : 32;
	} fields;
	uint32_t v;
} scu_ICDIPR23;

#define scu_ICDIPR23_PRIORITY_LSHIFT 0U
#define scu_ICDIPR23_PRIORITY_MASK 0x0U
#define scu_ICDIPR23_MASK 0x0U


// Interrupt Processor Targets Register 0
#define scu_ICDIPTR0_REG 0x1800U
typedef union scu_ICDIPTR0
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_3 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_2 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_1 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_0 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR0;

#define scu_ICDIPTR0_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR0_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR0_TARGET_3_LSHIFT 24U
#define scu_ICDIPTR0_TARGET_3_MASK 0x3000000U
#define scu_ICDIPTR0_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR0_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR0_TARGET_2_LSHIFT 16U
#define scu_ICDIPTR0_TARGET_2_MASK 0x30000U
#define scu_ICDIPTR0_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR0_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR0_TARGET_1_LSHIFT 8U
#define scu_ICDIPTR0_TARGET_1_MASK 0x300U
#define scu_ICDIPTR0_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR0_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR0_TARGET_0_LSHIFT 0U
#define scu_ICDIPTR0_TARGET_0_MASK 0x3U
#define scu_ICDIPTR0_MASK 0x3030303U


// Interrupt Processor Targets Register 1
#define scu_ICDIPTR1_REG 0x1804U
typedef union scu_ICDIPTR1
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_7 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_6 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_5 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_4 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR1;

#define scu_ICDIPTR1_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR1_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR1_TARGET_7_LSHIFT 24U
#define scu_ICDIPTR1_TARGET_7_MASK 0x3000000U
#define scu_ICDIPTR1_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR1_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR1_TARGET_6_LSHIFT 16U
#define scu_ICDIPTR1_TARGET_6_MASK 0x30000U
#define scu_ICDIPTR1_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR1_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR1_TARGET_5_LSHIFT 8U
#define scu_ICDIPTR1_TARGET_5_MASK 0x300U
#define scu_ICDIPTR1_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR1_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR1_TARGET_4_LSHIFT 0U
#define scu_ICDIPTR1_TARGET_4_MASK 0x3U
#define scu_ICDIPTR1_MASK 0x3030303U


// Interrupt Processor Targets Register 2
#define scu_ICDIPTR2_REG 0x1808U
typedef union scu_ICDIPTR2
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_11 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_10 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_9 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_8 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR2;

#define scu_ICDIPTR2_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR2_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR2_TARGET_11_LSHIFT 24U
#define scu_ICDIPTR2_TARGET_11_MASK 0x3000000U
#define scu_ICDIPTR2_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR2_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR2_TARGET_10_LSHIFT 16U
#define scu_ICDIPTR2_TARGET_10_MASK 0x30000U
#define scu_ICDIPTR2_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR2_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR2_TARGET_9_LSHIFT 8U
#define scu_ICDIPTR2_TARGET_9_MASK 0x300U
#define scu_ICDIPTR2_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR2_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR2_TARGET_8_LSHIFT 0U
#define scu_ICDIPTR2_TARGET_8_MASK 0x3U
#define scu_ICDIPTR2_MASK 0x3030303U


// Interrupt Processor Targets Register 3
#define scu_ICDIPTR3_REG 0x180cU
typedef union scu_ICDIPTR3
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_15 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_14 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_13 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_12 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR3;

#define scu_ICDIPTR3_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR3_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR3_TARGET_15_LSHIFT 24U
#define scu_ICDIPTR3_TARGET_15_MASK 0x3000000U
#define scu_ICDIPTR3_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR3_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR3_TARGET_14_LSHIFT 16U
#define scu_ICDIPTR3_TARGET_14_MASK 0x30000U
#define scu_ICDIPTR3_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR3_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR3_TARGET_13_LSHIFT 8U
#define scu_ICDIPTR3_TARGET_13_MASK 0x300U
#define scu_ICDIPTR3_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR3_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR3_TARGET_12_LSHIFT 0U
#define scu_ICDIPTR3_TARGET_12_MASK 0x3U
#define scu_ICDIPTR3_MASK 0x3030303U


// Interrupt Processor Targets Register 4
#define scu_ICDIPTR4_REG 0x1810U
typedef union scu_ICDIPTR4
{
	struct
	{
		uint32_t RESERVED_0 : 32;
	} fields;
	uint32_t v;
} scu_ICDIPTR4;

#define scu_ICDIPTR4_RESERVED_0_LSHIFT 0U
#define scu_ICDIPTR4_RESERVED_0_MASK 0x0U
#define scu_ICDIPTR4_MASK 0x0U


// Interrupt Processor Targets Register 5
#define scu_ICDIPTR5_REG 0x1814U
typedef union scu_ICDIPTR5
{
	struct
	{
		uint32_t RESERVED_0 : 32;
	} fields;
	uint32_t v;
} scu_ICDIPTR5;

#define scu_ICDIPTR5_RESERVED_0_LSHIFT 0U
#define scu_ICDIPTR5_RESERVED_0_MASK 0x0U
#define scu_ICDIPTR5_MASK 0x0U


// Interrupt Processor Targets Register 6
#define scu_ICDIPTR6_REG 0x1818U
typedef union scu_ICDIPTR6
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_27 : 2;
		uint32_t RESERVED_1 : 24;
	} fields;
	uint32_t v;
} scu_ICDIPTR6;

#define scu_ICDIPTR6_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR6_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR6_TARGET_27_LSHIFT 24U
#define scu_ICDIPTR6_TARGET_27_MASK 0x3000000U
#define scu_ICDIPTR6_RESERVED_1_LSHIFT 0U
#define scu_ICDIPTR6_RESERVED_1_MASK 0xffffffU
#define scu_ICDIPTR6_MASK 0x3000000U


// Interrupt Processor Targets Register 7
#define scu_ICDIPTR7_REG 0x181cU
typedef union scu_ICDIPTR7
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_31 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_30 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_29 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_28 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR7;

#define scu_ICDIPTR7_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR7_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR7_TARGET_31_LSHIFT 24U
#define scu_ICDIPTR7_TARGET_31_MASK 0x3000000U
#define scu_ICDIPTR7_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR7_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR7_TARGET_30_LSHIFT 16U
#define scu_ICDIPTR7_TARGET_30_MASK 0x30000U
#define scu_ICDIPTR7_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR7_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR7_TARGET_29_LSHIFT 8U
#define scu_ICDIPTR7_TARGET_29_MASK 0x300U
#define scu_ICDIPTR7_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR7_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR7_TARGET_28_LSHIFT 0U
#define scu_ICDIPTR7_TARGET_28_MASK 0x3U
#define scu_ICDIPTR7_MASK 0x3030303U


// Interrupt Processor Targets Register 8
#define scu_ICDIPTR8_REG 0x1820U
typedef union scu_ICDIPTR8
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_35 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_34 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_33 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_32 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR8;

#define scu_ICDIPTR8_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR8_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR8_TARGET_35_LSHIFT 24U
#define scu_ICDIPTR8_TARGET_35_MASK 0x3000000U
#define scu_ICDIPTR8_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR8_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR8_TARGET_34_LSHIFT 16U
#define scu_ICDIPTR8_TARGET_34_MASK 0x30000U
#define scu_ICDIPTR8_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR8_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR8_TARGET_33_LSHIFT 8U
#define scu_ICDIPTR8_TARGET_33_MASK 0x300U
#define scu_ICDIPTR8_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR8_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR8_TARGET_32_LSHIFT 0U
#define scu_ICDIPTR8_TARGET_32_MASK 0x3U
#define scu_ICDIPTR8_MASK 0x3030303U


// Interrupt Processor Targets Register 9
#define scu_ICDIPTR9_REG 0x1824U
typedef union scu_ICDIPTR9
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_39 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_38 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_37 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_36 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR9;

#define scu_ICDIPTR9_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR9_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR9_TARGET_39_LSHIFT 24U
#define scu_ICDIPTR9_TARGET_39_MASK 0x3000000U
#define scu_ICDIPTR9_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR9_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR9_TARGET_38_LSHIFT 16U
#define scu_ICDIPTR9_TARGET_38_MASK 0x30000U
#define scu_ICDIPTR9_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR9_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR9_TARGET_37_LSHIFT 8U
#define scu_ICDIPTR9_TARGET_37_MASK 0x300U
#define scu_ICDIPTR9_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR9_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR9_TARGET_36_LSHIFT 0U
#define scu_ICDIPTR9_TARGET_36_MASK 0x3U
#define scu_ICDIPTR9_MASK 0x3030303U


// Interrupt Processor Targets Register 10
#define scu_ICDIPTR10_REG 0x1828U
typedef union scu_ICDIPTR10
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_43 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_42 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_41 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_40 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR10;

#define scu_ICDIPTR10_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR10_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR10_TARGET_43_LSHIFT 24U
#define scu_ICDIPTR10_TARGET_43_MASK 0x3000000U
#define scu_ICDIPTR10_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR10_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR10_TARGET_42_LSHIFT 16U
#define scu_ICDIPTR10_TARGET_42_MASK 0x30000U
#define scu_ICDIPTR10_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR10_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR10_TARGET_41_LSHIFT 8U
#define scu_ICDIPTR10_TARGET_41_MASK 0x300U
#define scu_ICDIPTR10_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR10_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR10_TARGET_40_LSHIFT 0U
#define scu_ICDIPTR10_TARGET_40_MASK 0x3U
#define scu_ICDIPTR10_MASK 0x3030303U


// Interrupt Processor Targets Register 11
#define scu_ICDIPTR11_REG 0x182cU
typedef union scu_ICDIPTR11
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_47 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_46 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_45 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_44 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR11;

#define scu_ICDIPTR11_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR11_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR11_TARGET_47_LSHIFT 24U
#define scu_ICDIPTR11_TARGET_47_MASK 0x3000000U
#define scu_ICDIPTR11_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR11_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR11_TARGET_46_LSHIFT 16U
#define scu_ICDIPTR11_TARGET_46_MASK 0x30000U
#define scu_ICDIPTR11_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR11_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR11_TARGET_45_LSHIFT 8U
#define scu_ICDIPTR11_TARGET_45_MASK 0x300U
#define scu_ICDIPTR11_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR11_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR11_TARGET_44_LSHIFT 0U
#define scu_ICDIPTR11_TARGET_44_MASK 0x3U
#define scu_ICDIPTR11_MASK 0x3030303U


// Interrupt Processor Targets Register 12
#define scu_ICDIPTR12_REG 0x1830U
typedef union scu_ICDIPTR12
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_51 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_50 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_49 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_48 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR12;

#define scu_ICDIPTR12_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR12_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR12_TARGET_51_LSHIFT 24U
#define scu_ICDIPTR12_TARGET_51_MASK 0x3000000U
#define scu_ICDIPTR12_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR12_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR12_TARGET_50_LSHIFT 16U
#define scu_ICDIPTR12_TARGET_50_MASK 0x30000U
#define scu_ICDIPTR12_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR12_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR12_TARGET_49_LSHIFT 8U
#define scu_ICDIPTR12_TARGET_49_MASK 0x300U
#define scu_ICDIPTR12_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR12_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR12_TARGET_48_LSHIFT 0U
#define scu_ICDIPTR12_TARGET_48_MASK 0x3U
#define scu_ICDIPTR12_MASK 0x3030303U


// Interrupt Processor Targets Register 13
#define scu_ICDIPTR13_REG 0x1834U
typedef union scu_ICDIPTR13
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_55 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_54 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_53 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_52 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR13;

#define scu_ICDIPTR13_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR13_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR13_TARGET_55_LSHIFT 24U
#define scu_ICDIPTR13_TARGET_55_MASK 0x3000000U
#define scu_ICDIPTR13_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR13_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR13_TARGET_54_LSHIFT 16U
#define scu_ICDIPTR13_TARGET_54_MASK 0x30000U
#define scu_ICDIPTR13_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR13_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR13_TARGET_53_LSHIFT 8U
#define scu_ICDIPTR13_TARGET_53_MASK 0x300U
#define scu_ICDIPTR13_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR13_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR13_TARGET_52_LSHIFT 0U
#define scu_ICDIPTR13_TARGET_52_MASK 0x3U
#define scu_ICDIPTR13_MASK 0x3030303U


// Interrupt Processor Targets Register 14
#define scu_ICDIPTR14_REG 0x1838U
typedef union scu_ICDIPTR14
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_59 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_58 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_57 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_56 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR14;

#define scu_ICDIPTR14_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR14_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR14_TARGET_59_LSHIFT 24U
#define scu_ICDIPTR14_TARGET_59_MASK 0x3000000U
#define scu_ICDIPTR14_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR14_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR14_TARGET_58_LSHIFT 16U
#define scu_ICDIPTR14_TARGET_58_MASK 0x30000U
#define scu_ICDIPTR14_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR14_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR14_TARGET_57_LSHIFT 8U
#define scu_ICDIPTR14_TARGET_57_MASK 0x300U
#define scu_ICDIPTR14_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR14_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR14_TARGET_56_LSHIFT 0U
#define scu_ICDIPTR14_TARGET_56_MASK 0x3U
#define scu_ICDIPTR14_MASK 0x3030303U


// Interrupt Processor Targets Register 15
#define scu_ICDIPTR15_REG 0x183cU
typedef union scu_ICDIPTR15
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_63 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_62 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_61 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_60 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR15;

#define scu_ICDIPTR15_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR15_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR15_TARGET_63_LSHIFT 24U
#define scu_ICDIPTR15_TARGET_63_MASK 0x3000000U
#define scu_ICDIPTR15_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR15_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR15_TARGET_62_LSHIFT 16U
#define scu_ICDIPTR15_TARGET_62_MASK 0x30000U
#define scu_ICDIPTR15_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR15_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR15_TARGET_61_LSHIFT 8U
#define scu_ICDIPTR15_TARGET_61_MASK 0x300U
#define scu_ICDIPTR15_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR15_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR15_TARGET_60_LSHIFT 0U
#define scu_ICDIPTR15_TARGET_60_MASK 0x3U
#define scu_ICDIPTR15_MASK 0x3030303U


// Interrupt Processor Targets Register 16
#define scu_ICDIPTR16_REG 0x1840U
typedef union scu_ICDIPTR16
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_67 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_66 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_65 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_64 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR16;

#define scu_ICDIPTR16_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR16_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR16_TARGET_67_LSHIFT 24U
#define scu_ICDIPTR16_TARGET_67_MASK 0x3000000U
#define scu_ICDIPTR16_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR16_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR16_TARGET_66_LSHIFT 16U
#define scu_ICDIPTR16_TARGET_66_MASK 0x30000U
#define scu_ICDIPTR16_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR16_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR16_TARGET_65_LSHIFT 8U
#define scu_ICDIPTR16_TARGET_65_MASK 0x300U
#define scu_ICDIPTR16_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR16_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR16_TARGET_64_LSHIFT 0U
#define scu_ICDIPTR16_TARGET_64_MASK 0x3U
#define scu_ICDIPTR16_MASK 0x3030303U


// Interrupt Processor Targets Register 17
#define scu_ICDIPTR17_REG 0x1844U
typedef union scu_ICDIPTR17
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_71 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_70 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_69 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_68 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR17;

#define scu_ICDIPTR17_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR17_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR17_TARGET_71_LSHIFT 24U
#define scu_ICDIPTR17_TARGET_71_MASK 0x3000000U
#define scu_ICDIPTR17_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR17_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR17_TARGET_70_LSHIFT 16U
#define scu_ICDIPTR17_TARGET_70_MASK 0x30000U
#define scu_ICDIPTR17_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR17_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR17_TARGET_69_LSHIFT 8U
#define scu_ICDIPTR17_TARGET_69_MASK 0x300U
#define scu_ICDIPTR17_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR17_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR17_TARGET_68_LSHIFT 0U
#define scu_ICDIPTR17_TARGET_68_MASK 0x3U
#define scu_ICDIPTR17_MASK 0x3030303U


// Interrupt Processor Targets Register 18
#define scu_ICDIPTR18_REG 0x1848U
typedef union scu_ICDIPTR18
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_75 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_74 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_73 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_72 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR18;

#define scu_ICDIPTR18_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR18_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR18_TARGET_75_LSHIFT 24U
#define scu_ICDIPTR18_TARGET_75_MASK 0x3000000U
#define scu_ICDIPTR18_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR18_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR18_TARGET_74_LSHIFT 16U
#define scu_ICDIPTR18_TARGET_74_MASK 0x30000U
#define scu_ICDIPTR18_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR18_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR18_TARGET_73_LSHIFT 8U
#define scu_ICDIPTR18_TARGET_73_MASK 0x300U
#define scu_ICDIPTR18_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR18_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR18_TARGET_72_LSHIFT 0U
#define scu_ICDIPTR18_TARGET_72_MASK 0x3U
#define scu_ICDIPTR18_MASK 0x3030303U


// Interrupt Processor Targets Register 19
#define scu_ICDIPTR19_REG 0x184cU
typedef union scu_ICDIPTR19
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_79 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_78 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_77 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_76 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR19;

#define scu_ICDIPTR19_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR19_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR19_TARGET_79_LSHIFT 24U
#define scu_ICDIPTR19_TARGET_79_MASK 0x3000000U
#define scu_ICDIPTR19_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR19_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR19_TARGET_78_LSHIFT 16U
#define scu_ICDIPTR19_TARGET_78_MASK 0x30000U
#define scu_ICDIPTR19_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR19_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR19_TARGET_77_LSHIFT 8U
#define scu_ICDIPTR19_TARGET_77_MASK 0x300U
#define scu_ICDIPTR19_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR19_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR19_TARGET_76_LSHIFT 0U
#define scu_ICDIPTR19_TARGET_76_MASK 0x3U
#define scu_ICDIPTR19_MASK 0x3030303U


// Interrupt Processor Targets Register 20
#define scu_ICDIPTR20_REG 0x1850U
typedef union scu_ICDIPTR20
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_83 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_82 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_81 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_80 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR20;

#define scu_ICDIPTR20_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR20_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR20_TARGET_83_LSHIFT 24U
#define scu_ICDIPTR20_TARGET_83_MASK 0x3000000U
#define scu_ICDIPTR20_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR20_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR20_TARGET_82_LSHIFT 16U
#define scu_ICDIPTR20_TARGET_82_MASK 0x30000U
#define scu_ICDIPTR20_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR20_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR20_TARGET_81_LSHIFT 8U
#define scu_ICDIPTR20_TARGET_81_MASK 0x300U
#define scu_ICDIPTR20_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR20_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR20_TARGET_80_LSHIFT 0U
#define scu_ICDIPTR20_TARGET_80_MASK 0x3U
#define scu_ICDIPTR20_MASK 0x3030303U


// Interrupt Processor Targets Register 21
#define scu_ICDIPTR21_REG 0x1854U
typedef union scu_ICDIPTR21
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_87 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_86 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_85 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_84 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR21;

#define scu_ICDIPTR21_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR21_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR21_TARGET_87_LSHIFT 24U
#define scu_ICDIPTR21_TARGET_87_MASK 0x3000000U
#define scu_ICDIPTR21_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR21_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR21_TARGET_86_LSHIFT 16U
#define scu_ICDIPTR21_TARGET_86_MASK 0x30000U
#define scu_ICDIPTR21_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR21_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR21_TARGET_85_LSHIFT 8U
#define scu_ICDIPTR21_TARGET_85_MASK 0x300U
#define scu_ICDIPTR21_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR21_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR21_TARGET_84_LSHIFT 0U
#define scu_ICDIPTR21_TARGET_84_MASK 0x3U
#define scu_ICDIPTR21_MASK 0x3030303U


// Interrupt Processor Targets Register 22
#define scu_ICDIPTR22_REG 0x1858U
typedef union scu_ICDIPTR22
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_91 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_90 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_89 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_88 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR22;

#define scu_ICDIPTR22_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR22_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR22_TARGET_91_LSHIFT 24U
#define scu_ICDIPTR22_TARGET_91_MASK 0x3000000U
#define scu_ICDIPTR22_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR22_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR22_TARGET_90_LSHIFT 16U
#define scu_ICDIPTR22_TARGET_90_MASK 0x30000U
#define scu_ICDIPTR22_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR22_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR22_TARGET_89_LSHIFT 8U
#define scu_ICDIPTR22_TARGET_89_MASK 0x300U
#define scu_ICDIPTR22_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR22_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR22_TARGET_88_LSHIFT 0U
#define scu_ICDIPTR22_TARGET_88_MASK 0x3U
#define scu_ICDIPTR22_MASK 0x3030303U


// Interrupt Processor Targets Register 23
#define scu_ICDIPTR23_REG 0x185cU
typedef union scu_ICDIPTR23
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGET_95 : 2;
		uint32_t RESERVED_1 : 6;
		uint32_t TARGET_94 : 2;
		uint32_t RESERVED_2 : 6;
		uint32_t TARGET_93 : 2;
		uint32_t RESERVED_3 : 6;
		uint32_t TARGET_92 : 2;
	} fields;
	uint32_t v;
} scu_ICDIPTR23;

#define scu_ICDIPTR23_RESERVED_0_LSHIFT 26U
#define scu_ICDIPTR23_RESERVED_0_MASK 0xfc000000U
#define scu_ICDIPTR23_TARGET_95_LSHIFT 24U
#define scu_ICDIPTR23_TARGET_95_MASK 0x3000000U
#define scu_ICDIPTR23_RESERVED_1_LSHIFT 18U
#define scu_ICDIPTR23_RESERVED_1_MASK 0xfc0000U
#define scu_ICDIPTR23_TARGET_94_LSHIFT 16U
#define scu_ICDIPTR23_TARGET_94_MASK 0x30000U
#define scu_ICDIPTR23_RESERVED_2_LSHIFT 10U
#define scu_ICDIPTR23_RESERVED_2_MASK 0xfc00U
#define scu_ICDIPTR23_TARGET_93_LSHIFT 8U
#define scu_ICDIPTR23_TARGET_93_MASK 0x300U
#define scu_ICDIPTR23_RESERVED_3_LSHIFT 2U
#define scu_ICDIPTR23_RESERVED_3_MASK 0xfcU
#define scu_ICDIPTR23_TARGET_92_LSHIFT 0U
#define scu_ICDIPTR23_TARGET_92_MASK 0x3U
#define scu_ICDIPTR23_MASK 0x3030303U


// Interrupt Configuration Register 0
#define scu_ICDICFR0_REG 0x1c00U
typedef union scu_ICDICFR0
{
	struct
	{
		uint32_t CONFIG_15 : 2;
		uint32_t CONFIG_14 : 2;
		uint32_t CONFIG_13 : 2;
		uint32_t CONFIG_12 : 2;
		uint32_t CONFIG_11 : 2;
		uint32_t CONFIG_10 : 2;
		uint32_t CONFIG_9 : 2;
		uint32_t CONFIG_8 : 2;
		uint32_t CONFIG_7 : 2;
		uint32_t CONFIG_6 : 2;
		uint32_t CONFIG_5 : 2;
		uint32_t CONFIG_4 : 2;
		uint32_t CONFIG_3 : 2;
		uint32_t CONFIG_2 : 2;
		uint32_t CONFIG_1 : 2;
		uint32_t CONFIG_1 : 2;
	} fields;
	uint32_t v;
} scu_ICDICFR0;

#define scu_ICDICFR0_CONFIG_15_LSHIFT 30U
#define scu_ICDICFR0_CONFIG_15_MASK 0xc0000000U
#define scu_ICDICFR0_CONFIG_14_LSHIFT 28U
#define scu_ICDICFR0_CONFIG_14_MASK 0x30000000U
#define scu_ICDICFR0_CONFIG_13_LSHIFT 26U
#define scu_ICDICFR0_CONFIG_13_MASK 0xc000000U
#define scu_ICDICFR0_CONFIG_12_LSHIFT 24U
#define scu_ICDICFR0_CONFIG_12_MASK 0x3000000U
#define scu_ICDICFR0_CONFIG_11_LSHIFT 22U
#define scu_ICDICFR0_CONFIG_11_MASK 0xc00000U
#define scu_ICDICFR0_CONFIG_10_LSHIFT 20U
#define scu_ICDICFR0_CONFIG_10_MASK 0x300000U
#define scu_ICDICFR0_CONFIG_9_LSHIFT 18U
#define scu_ICDICFR0_CONFIG_9_MASK 0xc0000U
#define scu_ICDICFR0_CONFIG_8_LSHIFT 16U
#define scu_ICDICFR0_CONFIG_8_MASK 0x30000U
#define scu_ICDICFR0_CONFIG_7_LSHIFT 14U
#define scu_ICDICFR0_CONFIG_7_MASK 0xc000U
#define scu_ICDICFR0_CONFIG_6_LSHIFT 12U
#define scu_ICDICFR0_CONFIG_6_MASK 0x3000U
#define scu_ICDICFR0_CONFIG_5_LSHIFT 10U
#define scu_ICDICFR0_CONFIG_5_MASK 0xc00U
#define scu_ICDICFR0_CONFIG_4_LSHIFT 8U
#define scu_ICDICFR0_CONFIG_4_MASK 0x300U
#define scu_ICDICFR0_CONFIG_3_LSHIFT 6U
#define scu_ICDICFR0_CONFIG_3_MASK 0xc0U
#define scu_ICDICFR0_CONFIG_2_LSHIFT 4U
#define scu_ICDICFR0_CONFIG_2_MASK 0x30U
#define scu_ICDICFR0_CONFIG_1_LSHIFT 2U
#define scu_ICDICFR0_CONFIG_1_MASK 0xcU
#define scu_ICDICFR0_CONFIG_1_LSHIFT 0U
#define scu_ICDICFR0_CONFIG_1_MASK 0x3U
#define scu_ICDICFR0_MASK 0xffffffffU


// Interrupt Configuration Register 1
#define scu_ICDICFR1_REG 0x1c04U
typedef union scu_ICDICFR1
{
	struct
	{
		uint32_t CONFIG_31 : 2;
		uint32_t CONFIG_30 : 2;
		uint32_t CONFIG_29 : 2;
		uint32_t CONFIG_28 : 2;
		uint32_t CONFIG_27 : 2;
		uint32_t CONFIG_26 : 2;
		uint32_t CONFIG_25 : 2;
		uint32_t CONFIG_24 : 2;
		uint32_t CONFIG_23 : 2;
		uint32_t CONFIG_22 : 2;
		uint32_t CONFIG_21 : 2;
		uint32_t CONFIG_20 : 2;
		uint32_t CONFIG_19 : 2;
		uint32_t CONFIG_18 : 2;
		uint32_t CONFIG_17 : 2;
		uint32_t CONFIG_16 : 2;
	} fields;
	uint32_t v;
} scu_ICDICFR1;

#define scu_ICDICFR1_CONFIG_31_LSHIFT 30U
#define scu_ICDICFR1_CONFIG_31_MASK 0xc0000000U
#define scu_ICDICFR1_CONFIG_30_LSHIFT 28U
#define scu_ICDICFR1_CONFIG_30_MASK 0x30000000U
#define scu_ICDICFR1_CONFIG_29_LSHIFT 26U
#define scu_ICDICFR1_CONFIG_29_MASK 0xc000000U
#define scu_ICDICFR1_CONFIG_28_LSHIFT 24U
#define scu_ICDICFR1_CONFIG_28_MASK 0x3000000U
#define scu_ICDICFR1_CONFIG_27_LSHIFT 22U
#define scu_ICDICFR1_CONFIG_27_MASK 0xc00000U
#define scu_ICDICFR1_CONFIG_26_LSHIFT 20U
#define scu_ICDICFR1_CONFIG_26_MASK 0x300000U
#define scu_ICDICFR1_CONFIG_25_LSHIFT 18U
#define scu_ICDICFR1_CONFIG_25_MASK 0xc0000U
#define scu_ICDICFR1_CONFIG_24_LSHIFT 16U
#define scu_ICDICFR1_CONFIG_24_MASK 0x30000U
#define scu_ICDICFR1_CONFIG_23_LSHIFT 14U
#define scu_ICDICFR1_CONFIG_23_MASK 0xc000U
#define scu_ICDICFR1_CONFIG_22_LSHIFT 12U
#define scu_ICDICFR1_CONFIG_22_MASK 0x3000U
#define scu_ICDICFR1_CONFIG_21_LSHIFT 10U
#define scu_ICDICFR1_CONFIG_21_MASK 0xc00U
#define scu_ICDICFR1_CONFIG_20_LSHIFT 8U
#define scu_ICDICFR1_CONFIG_20_MASK 0x300U
#define scu_ICDICFR1_CONFIG_19_LSHIFT 6U
#define scu_ICDICFR1_CONFIG_19_MASK 0xc0U
#define scu_ICDICFR1_CONFIG_18_LSHIFT 4U
#define scu_ICDICFR1_CONFIG_18_MASK 0x30U
#define scu_ICDICFR1_CONFIG_17_LSHIFT 2U
#define scu_ICDICFR1_CONFIG_17_MASK 0xcU
#define scu_ICDICFR1_CONFIG_16_LSHIFT 0U
#define scu_ICDICFR1_CONFIG_16_MASK 0x3U
#define scu_ICDICFR1_MASK 0xffffffffU


// Interrupt Configuration Register 2
#define scu_ICDICFR2_REG 0x1c08U
typedef union scu_ICDICFR2
{
	struct
	{
		uint32_t CONFIG_47 : 2;
		uint32_t CONFIG_46 : 2;
		uint32_t CONFIG_45 : 2;
		uint32_t CONFIG_44 : 2;
		uint32_t CONFIG_43 : 2;
		uint32_t CONFIG_42 : 2;
		uint32_t CONFIG_41 : 2;
		uint32_t CONFIG_40 : 2;
		uint32_t CONFIG_39 : 2;
		uint32_t CONFIG_38 : 2;
		uint32_t CONFIG_37 : 2;
		uint32_t CONFIG_36 : 2;
		uint32_t CONFIG_35 : 2;
		uint32_t CONFIG_34 : 2;
		uint32_t CONFIG_33 : 2;
		uint32_t CONFIG_32 : 2;
	} fields;
	uint32_t v;
} scu_ICDICFR2;

#define scu_ICDICFR2_CONFIG_47_LSHIFT 30U
#define scu_ICDICFR2_CONFIG_47_MASK 0xc0000000U
#define scu_ICDICFR2_CONFIG_46_LSHIFT 28U
#define scu_ICDICFR2_CONFIG_46_MASK 0x30000000U
#define scu_ICDICFR2_CONFIG_45_LSHIFT 26U
#define scu_ICDICFR2_CONFIG_45_MASK 0xc000000U
#define scu_ICDICFR2_CONFIG_44_LSHIFT 24U
#define scu_ICDICFR2_CONFIG_44_MASK 0x3000000U
#define scu_ICDICFR2_CONFIG_43_LSHIFT 22U
#define scu_ICDICFR2_CONFIG_43_MASK 0xc00000U
#define scu_ICDICFR2_CONFIG_42_LSHIFT 20U
#define scu_ICDICFR2_CONFIG_42_MASK 0x300000U
#define scu_ICDICFR2_CONFIG_41_LSHIFT 18U
#define scu_ICDICFR2_CONFIG_41_MASK 0xc0000U
#define scu_ICDICFR2_CONFIG_40_LSHIFT 16U
#define scu_ICDICFR2_CONFIG_40_MASK 0x30000U
#define scu_ICDICFR2_CONFIG_39_LSHIFT 14U
#define scu_ICDICFR2_CONFIG_39_MASK 0xc000U
#define scu_ICDICFR2_CONFIG_38_LSHIFT 12U
#define scu_ICDICFR2_CONFIG_38_MASK 0x3000U
#define scu_ICDICFR2_CONFIG_37_LSHIFT 10U
#define scu_ICDICFR2_CONFIG_37_MASK 0xc00U
#define scu_ICDICFR2_CONFIG_36_LSHIFT 8U
#define scu_ICDICFR2_CONFIG_36_MASK 0x300U
#define scu_ICDICFR2_CONFIG_35_LSHIFT 6U
#define scu_ICDICFR2_CONFIG_35_MASK 0xc0U
#define scu_ICDICFR2_CONFIG_34_LSHIFT 4U
#define scu_ICDICFR2_CONFIG_34_MASK 0x30U
#define scu_ICDICFR2_CONFIG_33_LSHIFT 2U
#define scu_ICDICFR2_CONFIG_33_MASK 0xcU
#define scu_ICDICFR2_CONFIG_32_LSHIFT 0U
#define scu_ICDICFR2_CONFIG_32_MASK 0x3U
#define scu_ICDICFR2_MASK 0xffffffffU


// Interrupt Configuration Register 3
#define scu_ICDICFR3_REG 0x1c0cU
typedef union scu_ICDICFR3
{
	struct
	{
		uint32_t CONFIG_63 : 2;
		uint32_t CONFIG_62 : 2;
		uint32_t CONFIG_61 : 2;
		uint32_t CONFIG_60 : 2;
		uint32_t CONFIG_59 : 2;
		uint32_t CONFIG_58 : 2;
		uint32_t CONFIG_57 : 2;
		uint32_t CONFIG_56 : 2;
		uint32_t CONFIG_55 : 2;
		uint32_t CONFIG_54 : 2;
		uint32_t CONFIG_53 : 2;
		uint32_t CONFIG_52 : 2;
		uint32_t CONFIG_51 : 2;
		uint32_t CONFIG_50 : 2;
		uint32_t CONFIG_48 : 2;
		uint32_t CONFIG_47 : 2;
	} fields;
	uint32_t v;
} scu_ICDICFR3;

#define scu_ICDICFR3_CONFIG_63_LSHIFT 30U
#define scu_ICDICFR3_CONFIG_63_MASK 0xc0000000U
#define scu_ICDICFR3_CONFIG_62_LSHIFT 28U
#define scu_ICDICFR3_CONFIG_62_MASK 0x30000000U
#define scu_ICDICFR3_CONFIG_61_LSHIFT 26U
#define scu_ICDICFR3_CONFIG_61_MASK 0xc000000U
#define scu_ICDICFR3_CONFIG_60_LSHIFT 24U
#define scu_ICDICFR3_CONFIG_60_MASK 0x3000000U
#define scu_ICDICFR3_CONFIG_59_LSHIFT 22U
#define scu_ICDICFR3_CONFIG_59_MASK 0xc00000U
#define scu_ICDICFR3_CONFIG_58_LSHIFT 20U
#define scu_ICDICFR3_CONFIG_58_MASK 0x300000U
#define scu_ICDICFR3_CONFIG_57_LSHIFT 18U
#define scu_ICDICFR3_CONFIG_57_MASK 0xc0000U
#define scu_ICDICFR3_CONFIG_56_LSHIFT 16U
#define scu_ICDICFR3_CONFIG_56_MASK 0x30000U
#define scu_ICDICFR3_CONFIG_55_LSHIFT 14U
#define scu_ICDICFR3_CONFIG_55_MASK 0xc000U
#define scu_ICDICFR3_CONFIG_54_LSHIFT 12U
#define scu_ICDICFR3_CONFIG_54_MASK 0x3000U
#define scu_ICDICFR3_CONFIG_53_LSHIFT 10U
#define scu_ICDICFR3_CONFIG_53_MASK 0xc00U
#define scu_ICDICFR3_CONFIG_52_LSHIFT 8U
#define scu_ICDICFR3_CONFIG_52_MASK 0x300U
#define scu_ICDICFR3_CONFIG_51_LSHIFT 6U
#define scu_ICDICFR3_CONFIG_51_MASK 0xc0U
#define scu_ICDICFR3_CONFIG_50_LSHIFT 4U
#define scu_ICDICFR3_CONFIG_50_MASK 0x30U
#define scu_ICDICFR3_CONFIG_48_LSHIFT 2U
#define scu_ICDICFR3_CONFIG_48_MASK 0xcU
#define scu_ICDICFR3_CONFIG_47_LSHIFT 0U
#define scu_ICDICFR3_CONFIG_47_MASK 0x3U
#define scu_ICDICFR3_MASK 0xffffffffU


// Interrupt Configuration Register 4
#define scu_ICDICFR4_REG 0x1c10U
typedef union scu_ICDICFR4
{
	struct
	{
		uint32_t CONFIG_79 : 2;
		uint32_t CONFIG_78 : 2;
		uint32_t CONFIG_77 : 2;
		uint32_t CONFIG_76 : 2;
		uint32_t CONFIG_75 : 2;
		uint32_t CONFIG_74 : 2;
		uint32_t CONFIG_73 : 2;
		uint32_t CONFIG_72 : 2;
		uint32_t CONFIG_71 : 2;
		uint32_t CONFIG_70 : 2;
		uint32_t CONFIG_69 : 2;
		uint32_t CONFIG_68 : 2;
		uint32_t CONFIG_67 : 2;
		uint32_t CONFIG_66 : 2;
		uint32_t CONFIG_65 : 2;
		uint32_t CONFIG_64 : 2;
	} fields;
	uint32_t v;
} scu_ICDICFR4;

#define scu_ICDICFR4_CONFIG_79_LSHIFT 30U
#define scu_ICDICFR4_CONFIG_79_MASK 0xc0000000U
#define scu_ICDICFR4_CONFIG_78_LSHIFT 28U
#define scu_ICDICFR4_CONFIG_78_MASK 0x30000000U
#define scu_ICDICFR4_CONFIG_77_LSHIFT 26U
#define scu_ICDICFR4_CONFIG_77_MASK 0xc000000U
#define scu_ICDICFR4_CONFIG_76_LSHIFT 24U
#define scu_ICDICFR4_CONFIG_76_MASK 0x3000000U
#define scu_ICDICFR4_CONFIG_75_LSHIFT 22U
#define scu_ICDICFR4_CONFIG_75_MASK 0xc00000U
#define scu_ICDICFR4_CONFIG_74_LSHIFT 20U
#define scu_ICDICFR4_CONFIG_74_MASK 0x300000U
#define scu_ICDICFR4_CONFIG_73_LSHIFT 18U
#define scu_ICDICFR4_CONFIG_73_MASK 0xc0000U
#define scu_ICDICFR4_CONFIG_72_LSHIFT 16U
#define scu_ICDICFR4_CONFIG_72_MASK 0x30000U
#define scu_ICDICFR4_CONFIG_71_LSHIFT 14U
#define scu_ICDICFR4_CONFIG_71_MASK 0xc000U
#define scu_ICDICFR4_CONFIG_70_LSHIFT 12U
#define scu_ICDICFR4_CONFIG_70_MASK 0x3000U
#define scu_ICDICFR4_CONFIG_69_LSHIFT 10U
#define scu_ICDICFR4_CONFIG_69_MASK 0xc00U
#define scu_ICDICFR4_CONFIG_68_LSHIFT 8U
#define scu_ICDICFR4_CONFIG_68_MASK 0x300U
#define scu_ICDICFR4_CONFIG_67_LSHIFT 6U
#define scu_ICDICFR4_CONFIG_67_MASK 0xc0U
#define scu_ICDICFR4_CONFIG_66_LSHIFT 4U
#define scu_ICDICFR4_CONFIG_66_MASK 0x30U
#define scu_ICDICFR4_CONFIG_65_LSHIFT 2U
#define scu_ICDICFR4_CONFIG_65_MASK 0xcU
#define scu_ICDICFR4_CONFIG_64_LSHIFT 0U
#define scu_ICDICFR4_CONFIG_64_MASK 0x3U
#define scu_ICDICFR4_MASK 0xffffffffU


// Interrupt Configuration Register 5
#define scu_ICDICFR5_REG 0x1c14U
typedef union scu_ICDICFR5
{
	struct
	{
		uint32_t CONFIG_95 : 2;
		uint32_t CONFIG_94 : 2;
		uint32_t CONFIG_93 : 2;
		uint32_t CONFIG_92 : 2;
		uint32_t CONFIG_91 : 2;
		uint32_t CONFIG_90 : 2;
		uint32_t CONFIG_89 : 2;
		uint32_t CONFIG_88 : 2;
		uint32_t CONFIG_87 : 2;
		uint32_t CONFIG_86 : 2;
		uint32_t CONFIG_85 : 2;
		uint32_t CONFIG_84 : 2;
		uint32_t CONFIG_83 : 2;
		uint32_t CONFIG_82 : 2;
		uint32_t CONFIG_81 : 2;
		uint32_t CONFIG_80 : 2;
	} fields;
	uint32_t v;
} scu_ICDICFR5;

#define scu_ICDICFR5_CONFIG_95_LSHIFT 30U
#define scu_ICDICFR5_CONFIG_95_MASK 0xc0000000U
#define scu_ICDICFR5_CONFIG_94_LSHIFT 28U
#define scu_ICDICFR5_CONFIG_94_MASK 0x30000000U
#define scu_ICDICFR5_CONFIG_93_LSHIFT 26U
#define scu_ICDICFR5_CONFIG_93_MASK 0xc000000U
#define scu_ICDICFR5_CONFIG_92_LSHIFT 24U
#define scu_ICDICFR5_CONFIG_92_MASK 0x3000000U
#define scu_ICDICFR5_CONFIG_91_LSHIFT 22U
#define scu_ICDICFR5_CONFIG_91_MASK 0xc00000U
#define scu_ICDICFR5_CONFIG_90_LSHIFT 20U
#define scu_ICDICFR5_CONFIG_90_MASK 0x300000U
#define scu_ICDICFR5_CONFIG_89_LSHIFT 18U
#define scu_ICDICFR5_CONFIG_89_MASK 0xc0000U
#define scu_ICDICFR5_CONFIG_88_LSHIFT 16U
#define scu_ICDICFR5_CONFIG_88_MASK 0x30000U
#define scu_ICDICFR5_CONFIG_87_LSHIFT 14U
#define scu_ICDICFR5_CONFIG_87_MASK 0xc000U
#define scu_ICDICFR5_CONFIG_86_LSHIFT 12U
#define scu_ICDICFR5_CONFIG_86_MASK 0x3000U
#define scu_ICDICFR5_CONFIG_85_LSHIFT 10U
#define scu_ICDICFR5_CONFIG_85_MASK 0xc00U
#define scu_ICDICFR5_CONFIG_84_LSHIFT 8U
#define scu_ICDICFR5_CONFIG_84_MASK 0x300U
#define scu_ICDICFR5_CONFIG_83_LSHIFT 6U
#define scu_ICDICFR5_CONFIG_83_MASK 0xc0U
#define scu_ICDICFR5_CONFIG_82_LSHIFT 4U
#define scu_ICDICFR5_CONFIG_82_MASK 0x30U
#define scu_ICDICFR5_CONFIG_81_LSHIFT 2U
#define scu_ICDICFR5_CONFIG_81_MASK 0xcU
#define scu_ICDICFR5_CONFIG_80_LSHIFT 0U
#define scu_ICDICFR5_CONFIG_80_MASK 0x3U
#define scu_ICDICFR5_MASK 0xffffffffU


// PPI Status Register
#define scu_PPI_STATUS_REG 0x1d00U
typedef union scu_PPI_STATUS
{
	struct
	{
		uint32_t RESERVED_0 : 16;
		uint32_t PPI_STATUS : 5;
		uint32_t RESERVED_1 : 11;
	} fields;
	uint32_t v;
} scu_PPI_STATUS;

#define scu_PPI_STATUS_RESERVED_0_LSHIFT 16U
#define scu_PPI_STATUS_RESERVED_0_MASK 0xffff0000U
#define scu_PPI_STATUS_PPI_STATUS_LSHIFT 11U
#define scu_PPI_STATUS_PPI_STATUS_MASK 0xf800U
#define scu_PPI_STATUS_RESERVED_1_LSHIFT 0U
#define scu_PPI_STATUS_RESERVED_1_MASK 0x7ffU
#define scu_PPI_STATUS_MASK 0xf800U


// SPI Status Register 0
#define scu_SPI_STATUS_0_REG 0x1d04U
typedef union scu_SPI_STATUS_0
{
	struct
	{
		uint32_t SPI_STATUS : 32;
	} fields;
	uint32_t v;
} scu_SPI_STATUS_0;

#define scu_SPI_STATUS_0_SPI_STATUS_LSHIFT 0U
#define scu_SPI_STATUS_0_SPI_STATUS_MASK 0x0U
#define scu_SPI_STATUS_0_MASK 0x0U


// SPI Status Register 1
#define scu_SPI_STATUS_1_REG 0x1d08U
typedef union scu_SPI_STATUS_1
{
	struct
	{
		uint32_t SPI_STATUS : 32;
	} fields;
	uint32_t v;
} scu_SPI_STATUS_1;

#define scu_SPI_STATUS_1_SPI_STATUS_LSHIFT 0U
#define scu_SPI_STATUS_1_SPI_STATUS_MASK 0x0U
#define scu_SPI_STATUS_1_MASK 0x0U


// Software Generated Interrupt Register
#define scu_ICDSGIR_REG 0x1f00U
typedef union scu_ICDSGIR
{
	struct
	{
		uint32_t RESERVED_0 : 6;
		uint32_t TARGETLISTFILTER : 2;
		uint32_t CPUTARGETLIST : 8;
		uint32_t SATT : 1;
		uint32_t RESERVED_1 : 11;
		uint32_t SGIINTID : 4;
	} fields;
	uint32_t v;
} scu_ICDSGIR;

#define scu_ICDSGIR_RESERVED_0_LSHIFT 26U
#define scu_ICDSGIR_RESERVED_0_MASK 0xfc000000U
#define scu_ICDSGIR_TARGETLISTFILTER_LSHIFT 24U
#define scu_ICDSGIR_TARGETLISTFILTER_MASK 0x3000000U
#define scu_ICDSGIR_CPUTARGETLIST_LSHIFT 16U
#define scu_ICDSGIR_CPUTARGETLIST_MASK 0xff0000U
#define scu_ICDSGIR_SATT_LSHIFT 15U
#define scu_ICDSGIR_SATT 0x8000U
#define scu_ICDSGIR_SATT_MASK 0x8000U
#define scu_ICDSGIR_RESERVED_1_LSHIFT 4U
#define scu_ICDSGIR_RESERVED_1_MASK 0x7ff0U
#define scu_ICDSGIR_SGIINTID_LSHIFT 0U
#define scu_ICDSGIR_SGIINTID_MASK 0xfU
#define scu_ICDSGIR_MASK 0x3ff800fU


// Peripheral ID4
#define scu_ICPIDR4_REG 0x1fd0U
typedef union scu_ICPIDR4
{
	struct
	{
		uint32_t RESERVED_0 : 28;
		uint32_t CONTINUATIONCODE : 4;
	} fields;
	uint32_t v;
} scu_ICPIDR4;

#define scu_ICPIDR4_RESERVED_0_LSHIFT 4U
#define scu_ICPIDR4_RESERVED_0_MASK 0xfffffff0U
#define scu_ICPIDR4_CONTINUATIONCODE_LSHIFT 0U
#define scu_ICPIDR4_CONTINUATIONCODE_MASK 0xfU
#define scu_ICPIDR4_MASK 0xfU


// Peripheral ID5
#define scu_ICPIDR5_REG 0x1fd4U
typedef union scu_ICPIDR5
{
	struct
	{
		uint32_t RESERVED_0 : 32;
	} fields;
	uint32_t v;
} scu_ICPIDR5;

#define scu_ICPIDR5_RESERVED_0_LSHIFT 0U
#define scu_ICPIDR5_RESERVED_0_MASK 0x0U
#define scu_ICPIDR5_MASK 0x0U


// Peripheral ID6
#define scu_ICPIDR6_REG 0x1fd8U
typedef union scu_ICPIDR6
{
	struct
	{
		uint32_t RESERVED_0 : 32;
	} fields;
	uint32_t v;
} scu_ICPIDR6;

#define scu_ICPIDR6_RESERVED_0_LSHIFT 0U
#define scu_ICPIDR6_RESERVED_0_MASK 0x0U
#define scu_ICPIDR6_MASK 0x0U


// Peripheral ID7
#define scu_ICPIDR7_REG 0x1fdcU
typedef union scu_ICPIDR7
{
	struct
	{
		uint32_t RESERVED_0 : 32;
	} fields;
	uint32_t v;
} scu_ICPIDR7;

#define scu_ICPIDR7_RESERVED_0_LSHIFT 0U
#define scu_ICPIDR7_RESERVED_0_MASK 0x0U
#define scu_ICPIDR7_MASK 0x0U


// Peripheral ID0
#define scu_ICPIDR0_REG 0x1fe0U
typedef union scu_ICPIDR0
{
	struct
	{
		uint32_t RESERVED_0 : 24;
		uint32_t DEVID_LOW : 8;
	} fields;
	uint32_t v;
} scu_ICPIDR0;

#define scu_ICPIDR0_RESERVED_0_LSHIFT 8U
#define scu_ICPIDR0_RESERVED_0_MASK 0xffffff00U
#define scu_ICPIDR0_DEVID_LOW_LSHIFT 0U
#define scu_ICPIDR0_DEVID_LOW_MASK 0xffU
#define scu_ICPIDR0_MASK 0xffU


// Peripheral ID1
#define scu_ICPIDR1_REG 0x1fe4U
typedef union scu_ICPIDR1
{
	struct
	{
		uint32_t RESERVED_0 : 24;
		uint32_t ARCHID_LOW : 4;
		uint32_t DEVID_HIGH : 4;
	} fields;
	uint32_t v;
} scu_ICPIDR1;

#define scu_ICPIDR1_RESERVED_0_LSHIFT 8U
#define scu_ICPIDR1_RESERVED_0_MASK 0xffffff00U
#define scu_ICPIDR1_ARCHID_LOW_LSHIFT 4U
#define scu_ICPIDR1_ARCHID_LOW_MASK 0xf0U
#define scu_ICPIDR1_DEVID_HIGH_LSHIFT 0U
#define scu_ICPIDR1_DEVID_HIGH_MASK 0xfU
#define scu_ICPIDR1_MASK 0xffU


// Peripheral ID2
#define scu_ICPIDR2_REG 0x1fe8U
typedef union scu_ICPIDR2
{
	struct
	{
		uint32_t RESERVED_0 : 24;
		uint32_t ARCHREV : 4;
		uint32_t USESJEPCODE : 1;
		uint32_t ARCHID_HIGH : 3;
	} fields;
	uint32_t v;
} scu_ICPIDR2;

#define scu_ICPIDR2_RESERVED_0_LSHIFT 8U
#define scu_ICPIDR2_RESERVED_0_MASK 0xffffff00U
#define scu_ICPIDR2_ARCHREV_LSHIFT 4U
#define scu_ICPIDR2_ARCHREV_MASK 0xf0U
#define scu_ICPIDR2_USESJEPCODE_LSHIFT 3U
#define scu_ICPIDR2_USESJEPCODE 0x8U
#define scu_ICPIDR2_USESJEPCODE_MASK 0x8U
#define scu_ICPIDR2_ARCHID_HIGH_LSHIFT 0U
#define scu_ICPIDR2_ARCHID_HIGH_MASK 0x7U
#define scu_ICPIDR2_MASK 0xffU


// Peripheral ID3
#define scu_ICPIDR3_REG 0x1fecU
typedef union scu_ICPIDR3
{
	struct
	{
		uint32_t RESERVED_0 : 24;
		uint32_t REVISION : 4;
		uint32_t RESERVED_1 : 4;
	} fields;
	uint32_t v;
} scu_ICPIDR3;

#define scu_ICPIDR3_RESERVED_0_LSHIFT 8U
#define scu_ICPIDR3_RESERVED_0_MASK 0xffffff00U
#define scu_ICPIDR3_REVISION_LSHIFT 4U
#define scu_ICPIDR3_REVISION_MASK 0xf0U
#define scu_ICPIDR3_RESERVED_1_LSHIFT 0U
#define scu_ICPIDR3_RESERVED_1_MASK 0xfU
#define scu_ICPIDR3_MASK 0xf0U


// Component ID0
#define scu_ICCIDR0_REG 0x1ff0U
typedef union scu_ICCIDR0
{
	struct
	{
		uint32_t PREAMBLE : 32;
	} fields;
	uint32_t v;
} scu_ICCIDR0;

#define scu_ICCIDR0_PREAMBLE_LSHIFT 0U
#define scu_ICCIDR0_PREAMBLE_MASK 0x0U
#define scu_ICCIDR0_MASK 0x0U


// Component ID1
#define scu_ICCIDR1_REG 0x1ff4U
typedef union scu_ICCIDR1
{
	struct
	{
		uint32_t PREAMBLE : 32;
	} fields;
	uint32_t v;
} scu_ICCIDR1;

#define scu_ICCIDR1_PREAMBLE_LSHIFT 0U
#define scu_ICCIDR1_PREAMBLE_MASK 0x0U
#define scu_ICCIDR1_MASK 0x0U


// Component ID2
#define scu_ICCIDR2_REG 0x1ff8U
typedef union scu_ICCIDR2
{
	struct
	{
		uint32_t PREAMBLE : 32;
	} fields;
	uint32_t v;
} scu_ICCIDR2;

#define scu_ICCIDR2_PREAMBLE_LSHIFT 0U
#define scu_ICCIDR2_PREAMBLE_MASK 0x0U
#define scu_ICCIDR2_MASK 0x0U


// Component ID3
#define scu_ICCIDR3_REG 0x1ffcU
typedef union scu_ICCIDR3
{
	struct
	{
		uint32_t PREAMBLE : 32;
	} fields;
	uint32_t v;
} scu_ICCIDR3;

#define scu_ICCIDR3_PREAMBLE_LSHIFT 0U
#define scu_ICCIDR3_PREAMBLE_MASK 0x0U
#define scu_ICCIDR3_MASK 0x0U


