//`define USE_CAN0
//`define USE_CAN1
//`define USE_ENET0
//`define USE_ENET1
//`define USE_DMA0
//`define USE_DMA1
//`define USE_DMA2
//`define USE_DMA3
//`define USE_GPIO
//`define USE_MIO
//`define USE_I2C0
//`define USE_I2C1
//`define USE_SDIO0
//`define USE_SDIO1
//`define USE_SPI0
//`define USE_SPI1
//`define USE_UART0
//`define USE_UART1
//`define USE_JTAG
//`define USE_TTC0
//`define USE_TTC1
//`define USE_TRACE
//`define USE_WATCHDOG
//`define USE_USB0
//`define USE_USB1
//`define USE_INTERRUPTS
//`define USE_PS_EVENTS
//`define USE_FPGA_IDLE
`define USE_FCLK0
//`define USE_FCLK1
//`define USE_FCLK2
//`define USE_FCLK3
`define PS_MASTER_AXI_GP0
//`define PS_MASTER_AXI_GP1
//`define PS_SLAVE_AXI_GP0
//`define PS_SLAVE_AXI_GP1
//`define PS_SLAVE_AXI_ACP
//`define PS_SLAVE_AXI_HP0
//`define PS_SLAVE_AXI_HP1
//`define PS_SLAVE_AXI_HP2
//`define PS_SLAVE_AXI_HP3
